#!/usr/bin/env python3
"""Generate ARC-AGI-2 Solver v3 notebook (valid JSON, nbformat 4)."""

import json

def L(*lines):
    """Wrap a list of code lines into a notebook source array (with trailing newlines)."""
    result = []
    for i, line in enumerate(lines):
        if i < len(lines) - 1:
            result.append(line + "\n")
        else:
            result.append(line)
    return result

def md(*lines):
    """Markdown source array."""
    return L(*lines)

def code(*lines):
    """Code source array."""
    return L(*lines)

def md_cell(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": md(*lines)}

def code_cell(*lines):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": code(*lines)}

# ============================================================================
# Build the notebook
# ============================================================================

cells = []

# ---- CELL 1: Title ----
cells.append(md_cell(
    "# ARC Prize 2026 \u2014 ARC-AGI-2 Solver v3 (Kaggle Notebook)",
    "",
    "## Architecture Overview",
    "",
    "This notebook implements a **multi-strategy tiered ensemble solver** combining heuristic pattern matching,",
    "object-centric reasoning, task similarity search, LLM code generation with self-consistency,",
    "evolutionary program synthesis, and test-time LoRA fine-tuning.",
    "",
    "### Key Improvements over v2",
    "",
    "| # | Improvement | Description |",
    "|---|------------|-------------|",
    "| 1 | **Grid Embedding & Similarity Search** | Build feature vectors from tasks; transfer solutions from similar training tasks |",
    "| 2 | **Object-Centric Reasoning** | Decompose grids into objects, detect consistent transforms (translate/scale/color/reshape) |",
    "| 3 | **70+ Heuristic Solvers** | v2's 38 base + morphological, sorting, compression, tile detection, distribution, 30+ composites |",
    "| 4 | **Self-Consistency LLM** | Generate 3 candidates at different temperatures; verify all; pick best |",
    "| 5 | **Test-Time LoRA Training** | Last-resort PEFT fine-tuning on task's training pairs (rank=8, 50 steps) |",
    "| 6 | **Improved Evolutionary Synthesis** | 15 population, 4 generations, new mutate_swap_lines operator |",
    "| 7 | **Tiered Ensemble Pipeline** | Heuristics \u2192 Objects \u2192 Similarity \u2192 LLM \u2192 Evolve \u2192 LoRA |",
    "",
    "### Pipeline",
    "",
    "```",
    "For each task:",
    "  1. Run 70+ heuristic solvers \u2192 if 100% match, use it",
    "  2. Try object-centric reasoning (consistent transform across train pairs)",
    "  3. Find similar training tasks \u2192 transfer their working heuristics",
    "  4. LLM self-consistency: 3 candidates at T=0.2, 0.4, 0.6 \u2192 verify all",
    "  5. Evolve LLM candidates (15 pop, 4 gens, swap-lines mutation)",
    "  6. Test-time LoRA training (last resort, 50 steps)",
    "  7. Pick top-2 distinct predictions for submission",
    "```",
    "",
    "### Kaggle Constraints",
    "- GPU: T4/P100 (16 GB), no internet",
    "- Time limit: ~12 hours",
    "- Output: `submission.json` with 2 attempts per task",
    "- Data: `/kaggle/input/arc-prize-2026-arc-agi-2/data/evaluation/` and `training/`",
))

# ---- CELL 2: Config & Imports ----
cells.append(code_cell(
    "# ============================================================================",
    "# CELL 1: Configuration, Imports & Constants",
    "# ============================================================================",
    "'''",
    "ARC-AGI-2 Solver v3 \u2014 Configuration & Imports",
    "",
    "Self-contained Kaggle notebook. Uses: transformers, torch, numpy, scipy, tqdm, peft.",
    "No internet access required; Qwen3-4B is pre-cached on Kaggle GPUs.",
    "'''",
    "",
    "import json",
    "import os",
    "import copy",
    "import time",
    "import sys",
    "import traceback",
    "import textwrap",
    "import threading",
    "import re",
    "import hashlib",
    "import random",
    "import math",
    "from pathlib import Path",
    "from collections import Counter, defaultdict, deque",
    "from typing import Any, Dict, List, Optional, Tuple, Callable",
    "from itertools import product as itertools_product",
    "",
    "import numpy as np",
    "",
    "# Lazy imports \u2014 only needed for LLM (GPU) path",
    "_HAS_TORCH = False",
    "_HAS_TRANSFORMERS = False",
    "_HAS_BNB = False",
    "_HAS_PEFT = False",
    "try:",
    "    import torch",
    "    _HAS_TORCH = True",
    "except ImportError:",
    "    pass",
    "try:",
    "    from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig",
    "    _HAS_TRANSFORMERS = True",
    "except ImportError:",
    "    pass",
    "try:",
    "    import bitsandbytes  # noqa: F401",
    "    _HAS_BNB = True",
    "except ImportError:",
    "    pass",
    "try:",
    "    from peft import LoraConfig, get_peft_model, TaskType",
    "    _HAS_PEFT = True",
    "except ImportError:",
    "    pass",
    "",
    "try:",
    "    from tqdm.auto import tqdm",
    "except ImportError:",
    "    def tqdm(iterable, **kwargs):",
    "        desc = kwargs.get('desc', '')",
    "        total = kwargs.get('total', len(iterable) if hasattr(iterable, '__len__') else None)",
    "        if desc:",
    '            print(f"{desc}...")',
    "        for item in iterable:",
    "            yield item",
    "",
    "# --------------------------------------------------------------------------",
    "# Paths (Kaggle)",
    "# --------------------------------------------------------------------------",
    'DATA_DIR = "/kaggle/input/arc-prize-2026-arc-agi-2"',
    'OUTPUT_PATH = "/kaggle/working/submission.json"',
    "",
    "# --------------------------------------------------------------------------",
    "# LLM settings",
    "# --------------------------------------------------------------------------",
    'MODEL_NAME = "Qwen/Qwen3-4B"',
    "QUANTIZATION_4BIT = True",
    "MAX_NEW_TOKENS = 2048",
    "MAX_INPUT_TOKENS = 30000",
    "",
    "# --------------------------------------------------------------------------",
    "# LoRA test-time training settings (v3 new)",
    "# --------------------------------------------------------------------------",
    "LORA_RANK = 8",
    "LORA_ALPHA = 16",
    "LORA_STEPS = 50",
    "LORA_LR = 5e-5",
    "LORA_TARGET_MODULES = ['q_proj', 'v_proj']",
    "",
    "# --------------------------------------------------------------------------",
    "# Solver settings",
    "# --------------------------------------------------------------------------",
    "CODE_TIMEOUT_SECONDS = 10",
    "MAX_LLM_TIME_SECONDS = 300",
    "NUM_SUBMISSION_ATTEMPTS = 2",
    "EVOLUTIONARY_POPULATION = 15    # v3: up from 12",
    "EVOLUTIONARY_GENERATIONS = 4    # v3: up from 3",
    "",
    "# --------------------------------------------------------------------------",
    "# ARC color palette (for prompt engineering)",
    "# --------------------------------------------------------------------------",
    "COLOR_NAMES = {",
    '    0: "black", 1: "blue", 2: "red", 3: "green", 4: "yellow",',
    '    5: "gray", 6: "magenta", 7: "orange", 8: "cyan", 9: "brown",',
    "}",
    "COLOR_NAME_TO_ID = {v: k for k, v in COLOR_NAMES.items()}",
    "",
    "# --------------------------------------------------------------------------",
    "# DreamCoder shared abstraction library",
    "# --------------------------------------------------------------------------",
    "ABSTRACTION_LIBRARY: Dict[str, str] = {}",
    "",
    'print(f"[CONFIG] Python {sys.version}")',
    'print(f"[CONFIG] Torch available: {_HAS_TORCH}")',
    'print(f"[CONFIG] Transformers available: {_HAS_TRANSFORMERS}")',
    'print(f"[CONFIG] BitsAndBytes available: {_HAS_BNB}")',
    'print(f"[CONFIG] PEFT available: {_HAS_PEFT}")',
    "if _HAS_TORCH:",
    '    print(f"[CONFIG] CUDA available: {torch.cuda.is_available()}")',
    "    if torch.cuda.is_available():",
    '        print(f"[CONFIG] GPU: {torch.cuda.get_device_name(0)}")',
    'print(f"[CONFIG] Model: {MODEL_NAME}")',
    'print(f"[CONFIG] NumPy: {np.__version__}")',
))

# ---- CELL 3: Grid Utilities (markdown) ----
cells.append(md_cell(
    "## Grid Utility Functions"
))

# ---- CELL 4: Grid utils (code) ----
cells.append(code_cell(
    "# ============================================================================",
    "# CELL 2: Grid Utility Functions",
    "# ============================================================================",
    "'''",
    "Core grid manipulation utilities used throughout the solver.",
    "All functions accept and return list-of-lists (not numpy arrays) for",
    "compatibility with ARC JSON format and exec-based code generation.",
    "'''",
    "",
    "def grid_to_str(grid: List[List[int]], label: str = '') -> str:",
    '    """Convert grid to multi-line string with optional label and dimensions."""',
    "    if not grid:",
    '        return f"{label}: (empty)"',
    "    rows = len(grid)",
    "    cols = len(grid[0]) if grid else 0",
    '    header = f"{label} ({rows}x{cols}):" if label else f"({rows}x{cols}):"',
    '    lines = [header]',
    "    for row in grid:",
    '        lines.append(" ".join(str(v) for v in row))',
    '    return "\\n".join(lines)',
    "",
    "",
    "def grids_equal(a: List[List[int]], b: List[List[int]]) -> bool:",
    '    """Check exact equality of two grids."""',
    "    if len(a) != len(b):",
    "        return False",
    "    for ra, rb in zip(a, b):",
    "        if len(ra) != len(rb):",
    "            return False",
    "        for va, vb in zip(ra, rb):",
    "            if va != vb:",
    "                return False",
    "    return True",
    "",
    "",
    "def grid_to_numpy(grid: List[List[int]]) -> np.ndarray:",
    "    return np.array(grid, dtype=np.int64)",
    "",
    "",
    "def numpy_to_grid(arr: np.ndarray) -> List[List[int]]:",
    "    return arr.astype(int).tolist()",
    "",
    "",
    "def normalize_grid(result: Any) -> Optional[List[List[int]]]:",
    '    """Coerce arbitrary return value into a valid grid (list-of-lists of ints 0\u20139)."""',
    "    if isinstance(result, list):",
    "        if all(isinstance(row, list) for row in result):",
    "            if all(isinstance(v, (int, np.integer)) for row in result for v in row):",
    "                return [[int(v) % 10 for v in row] for row in result]",
    "        if all(isinstance(row, (list, np.ndarray)) for row in result):",
    "            try:",
    "                return [[int(v) % 10 for v in row] for row in result]",
    "            except (TypeError, ValueError):",
    "                pass",
    "    if isinstance(result, np.ndarray):",
    "        if result.ndim == 2:",
    "            return result.astype(int).tolist()",
    "        elif result.ndim == 1:",
    "            return [result.astype(int).tolist()]",
    "    if isinstance(result, tuple):",
    "        return normalize_grid(list(result))",
    "    return None",
    "",
    "",
    "def ensure_grid(result: Any) -> List[List[int]]:",
    '    """Like normalize_grid but returns [[0]] on failure instead of None."""',
    "    g = normalize_grid(result)",
    "    return g if g is not None else [[0]]",
    "",
    "",
    "def grid_hash(grid: List[List[int]]) -> str:",
    '    """Deterministic hash of a grid for deduplication."""',
    '    s = json.dumps(grid, sort_keys=True)',
    '    return hashlib.md5(s.encode()).hexdigest()[:12]',
    "",
    "",
    "def grid_shape(grid: List[List[int]]) -> Tuple[int, int]:",
    "    if not grid:",
    "        return (0, 0)",
    "    return (len(grid), len(grid[0]))",
    "",
    "",
    "# --------------------------------------------------------------------------",
    "# Component analysis (flood fill)",
    "# --------------------------------------------------------------------------",
    "def find_components(grid: List[List[int]], connectivity: int = 4) -> List[List[Tuple[int, int]]]:",
    "    '''",
    "    Find connected components of non-zero cells using flood fill.",
    "    connectivity: 4 (up/down/left/right) or 8 (includes diagonals).",
    "    Returns list of components, each a list of (row, col) tuples.",
    "    '''",
    "    arr = grid_to_numpy(grid)",
    "    h, w = arr.shape",
    "    visited = np.zeros((h, w), dtype=bool)",
    "    components = []",
    "",
    "    if connectivity == 4:",
    "        neighbors = [(-1, 0), (1, 0), (0, -1), (0, 1)]",
    "    else:",
    "        neighbors = [(-1, 0), (1, 0), (0, -1), (0, 1),",
    "                     (-1, -1), (-1, 1), (1, -1), (1, 1)]",
    "",
    "    for r in range(h):",
    "        for c in range(w):",
    "            if arr[r, c] != 0 and not visited[r, c]:",
    "                color = int(arr[r, c])",
    "                component = []",
    "                stack = [(r, c)]",
    "                while stack:",
    "                    cr, cc = stack.pop()",
    "                    if cr < 0 or cr >= h or cc < 0 or cc >= w:",
    "                        continue",
    "                    if visited[cr, cc]:",
    "                        continue",
    "                    if arr[cr, cc] != color:",
    "                        continue",
    "                    visited[cr, cc] = True",
    "                    component.append((cr, cc))",
    "                    for dr, dc in neighbors:",
    "                        stack.append((cr + dr, cc + dc))",
    "                components.append(component)",
    "",
    "    return components",
    "",
    "",
    "def component_bounding_box(component: List[Tuple[int, int]]) -> Tuple[int, int, int, int]:",
    '    """Return (min_r, min_c, max_r, max_c) for a component."""',
    "    rows = [p[0] for p in component]",
    "    cols = [p[1] for p in component]",
    "    return (min(rows), min(cols), max(rows), max(cols))",
    "",
    "",
    "def extract_component_grid(grid: List[List[int]], component: List[Tuple[int, int]]) -> List[List[int]]:",
    '    """Extract a component from the grid into its own cropped sub-grid."""',
    "    min_r, min_c, max_r, max_c = component_bounding_box(component)",
    "    comp_set = set(component)",
    "    arr = grid_to_numpy(grid)",
    "    return arr[min_r:max_r+1, min_c:max_c+1].tolist()",
    "",
    "",
    "def count_colors(grid: List[List[int]]) -> Counter:",
    '    """Count occurrences of each color in the grid."""',
    "    arr = grid_to_numpy(grid)",
    "    flat = arr.flatten().tolist()",
    "    return Counter(int(v) for v in flat)",
    "",
    "",
    "# --------------------------------------------------------------------------",
    "# Grid feature extraction (for conditional logic & prompt engineering)",
    "# --------------------------------------------------------------------------",
    "def extract_grid_features(grid: List[List[int]]) -> Dict[str, Any]:",
    '    """',
    "    Extract comprehensive features from a grid for conditional routing",
    "    and LLM prompt enrichment.",
    "    '''",
    "    arr = grid_to_numpy(grid)",
    "    h, w = arr.shape",
    "    colors = count_colors(grid)",
    "    nonzero_colors = {c for c in colors if c != 0}",
    "    total_cells = h * w",
    "    nonzero_cells = sum(colors[c] for c in nonzero_colors)",
    "    density = nonzero_cells / max(total_cells, 1)",
    "    comps_4 = find_components(grid, 4)",
    "    comps_8 = find_components(grid, 8)",
    "",
    "    return {",
    "        'height': h, 'width': w, 'is_square': h == w,",
    "        'wider_than_tall': w > h, 'taller_than_wide': h > w,",
    "        'size_parity': (h * w) % 2,",
    "        'colors': dict(colors),",
    "        'nonzero_colors': nonzero_colors,",
    "        'num_colors': len(nonzero_colors),",
    "        'dominant_color': colors.most_common(1)[0][0] if colors else 0,",
    "        'density': density,",
    "        'num_components_4': len(comps_4),",
    "        'num_components_8': len(comps_8),",
    "        'nonzero_cells': nonzero_cells,",
    "        'sym_h': bool(np.array_equal(arr, arr[:, ::-1])),",
    "        'sym_v': bool(np.array_equal(arr, arr[::-1, :])),",
    "    }",
    "",
    "",
    "def describe_grid_natural_language(grid: List[List[int]], label: str = 'Grid') -> str:",
    '    """',
    "    Generate a natural-language description of the grid for LLM prompts.",
    "    Includes dimensions, colors, objects, and spatial layout.",
    "    '''",
    "    features = extract_grid_features(grid)",
    '    parts = [f"{label}: {features[\'height\']} rows x {features[\'width\']} cols"]',
    "",
    "    color_descs = []",
    "    for c in sorted(features['nonzero_colors']):",
    "        name = COLOR_NAMES.get(c, str(c))",
    "        count = features['colors'][c]",
    '        color_descs.append(f"{name}({c}) x{count}")',
    "    if color_descs:",
    '        parts.append(f"Colors: {\', \'.join(color_descs)}")',
    "    else:",
    '        parts.append("Colors: all black (empty)")',
    "",
    "    n_comp = features['num_components_4']",
    "    if n_comp > 0:",
    '        parts.append(f"Objects: {n_comp} connected component(s) (4-conn)")',
    "    else:",
    '        parts.append("Objects: none")',
    "",
    '    shape = "square" if features[\'is_square\'] else (',
    '        "wide" if features[\'wider_than_tall\'] else "tall")',
    '    parts.append(f"Shape: {shape}")',
    "",
    "    syms = []",
    "    if features['sym_h']:",
    '        syms.append("horizontal")',
    "    if features['sym_v']:",
    '        syms.append("vertical")',
    "    if syms:",
    '        parts.append(f"Symmetry: {\', \'.join(syms)}")',
    "",
    '    return " | ".join(parts)',
    "",
    "",
    'print("[UTILS] Grid utility functions loaded.")',
    'print(f"[UTILS] Color palette: {COLOR_NAMES}")',
))

# ---- CELL 5: Data Loading (markdown) ----
cells.append(md_cell(
    "## Data Loading"
))

# ---- CELL 6: Data loading (code) ----
cells.append(code_cell(
    "# ============================================================================",
    "# CELL 3: Data Loading",
    "# ============================================================================",
    "",
    'def load_task(filepath: str) -> Dict[str, Any]:',
    '    """Load a single ARC task JSON file."""',
    '    with open(filepath, "r") as f:',
    "        return json.load(f)",
    "",
    "",
    'def load_all_tasks(data_dir: str, split: str = "evaluation") -> Dict[str, Dict]:',
    '    """Load every task in a split directory."""',
    '    split_dir = os.path.join(data_dir, "data", split)',
    "    tasks = {}",
    "    if not os.path.isdir(split_dir):",
    '        print(f"[WARN] Directory not found: {split_dir}")',
    "        return tasks",
    "    for fname in sorted(os.listdir(split_dir)):",
    '        if fname.endswith(".json"):',
    '            task_id = fname.replace(".json", "")',
    "            tasks[task_id] = load_task(os.path.join(split_dir, fname))",
    "    return tasks",
    "",
    "",
    "def load_arc_data(data_dir: str) -> Tuple[Dict[str, Dict], Dict[str, Dict]]:",
    '    """Load both evaluation and training splits. Returns (eval_tasks, train_tasks)."""',
    '    eval_tasks = load_all_tasks(data_dir, "evaluation")',
    '    train_tasks = load_all_tasks(data_dir, "training")',
    '    print(f"[DATA] Loaded {len(eval_tasks)} evaluation, {len(train_tasks)} training tasks.")',
    "    return eval_tasks, train_tasks",
    "",
    "",
    "def print_task_summary(task: Dict, task_id: str = '') -> None:",
    '    """Print a concise summary of a task."""',
    '    n_train = len(task.get(\'train\', []))',
    '    n_test = len(task.get(\'test\', []))',
    "    if task_id:",
    '        print(f"  Task {task_id}: {n_train} train pairs, {n_test} test inputs")',
    '    for i, pair in enumerate(task.get(\'train\', [])):',
    '        inp_s = grid_shape(pair[\'input\'])',
    '        out_s = grid_shape(pair[\'output\'])',
    '        print(f"    Train {i+1}: {inp_s} \u2192 {out_s}")',
    '    for i, t in enumerate(task.get(\'test\', [])):',
    '        inp_s = grid_shape(t[\'input\'])',
    '        print(f"    Test {i+1}: input {inp_s}")',
    "",
    "",
    'print("[DATA] Data loading functions ready.")',
))

# ---- CELL 7: Grid Embedding & Similarity Search (markdown) ----
cells.append(md_cell(
    "## Grid Embedding & Similarity Search (NEW in v3)",
    "",
    "Builds a feature vector for each task from all training pairs, then uses cosine similarity",
    "to find the most similar training tasks. If a similar training task was solved by a heuristic,",
    "that same heuristic is tried on the evaluation task (transfer learning)."
))

# ---- CELL 8: Embedding & Similarity (code) ----
cells.append(code_cell(
    "# ============================================================================",
    "# CELL 4: Grid Embedding & Similarity Search (NEW v3)",
    "# ============================================================================",
    "'''",
    "Task embedding and similarity index for cross-task transfer learning.",
    "Computes a feature vector from all train pairs of a task, then uses",
    "cosine similarity to find similar solved training tasks.",
    "'''",
    "",
    "def compute_task_embedding(task: Dict) -> np.ndarray:",
    '    """',
    "    Compute a feature vector from all training pairs of a task.",
    "    Features: shape ratios, color counts, component counts, density, symmetry.",
    "    Returns a normalized float vector.",
    "    '''",
    "    features = []",
    '    pairs = task.get(\'train\', [])',
    "    if not pairs:",
    "        return np.zeros(32, dtype=np.float32)",
    "",
    "    for pair in pairs:",
    "        inp_f = extract_grid_features(pair['input'])",
    "        out_f = extract_grid_features(pair['output'])",
    "",
    "        # Shape features",
    "        inp_h, inp_w = inp_f['height'], inp_f['width']",
    "        out_h, out_w = out_f['height'], out_f['width']",
    "        max_dim = max(inp_h, inp_w, out_h, out_w, 1)",
    "        features.extend([",
    "            inp_h / 30.0, inp_w / 30.0,",
    "            out_h / 30.0, out_w / 30.0,",
    "            (out_h - inp_h) / max_dim,",
    "            (out_w - inp_w) / max_dim,",
    "        ])",
    "",
    "        # Color features",
    "        for c in range(10):",
    '            inp_c = inp_f[\'colors\'].get(c, 0)',
    '            out_c = out_f[\'colors\'].get(c, 0)',
    "            total = max(inp_h * inp_w, 1)",
    "            features.extend([inp_c / total, out_c / total])",
    "",
    "        # Component features",
    "        features.extend([",
    "            inp_f['num_components_4'] / 20.0,",
    "            inp_f['num_components_8'] / 20.0,",
    "            out_f['num_components_4'] / 20.0,",
    "            out_f['num_components_8'] / 20.0,",
    "            inp_f['density'],",
    "            out_f['density'],",
    "            float(inp_f['sym_h']), float(inp_f['sym_v']),",
    "            float(out_f['sym_h']), float(out_f['sym_v']),",
    "            inp_f['num_colors'] / 10.0,",
    "            out_f['num_colors'] / 10.0,",
    "        ])",
    "",
    "    # Pad/truncate to fixed size",
    "    vec = np.array(features[:64], dtype=np.float32)",
    "    if len(vec) < 64:",
    "        vec = np.pad(vec, (0, 64 - len(vec)))",
    "",
    "    # Normalize",
    "    norm = np.linalg.norm(vec)",
    "    if norm > 0:",
    "        vec = vec / norm",
    "    return vec",
    "",
    "",
    "def cosine_similarity(a: np.ndarray, b: np.ndarray) -> float:",
    '    """Compute cosine similarity between two vectors."""',
    "    dot = np.dot(a, b)",
    "    na = np.linalg.norm(a)",
    "    nb = np.linalg.norm(b)",
    "    if na == 0 or nb == 0:",
    "        return 0.0",
    "    return float(dot / (na * nb))",
    "",
    "",
    "class TaskSimilarityIndex:",
    '    """',
    "    Builds an index of training tasks with their embeddings and solved heuristics.",
    "    Can find similar training tasks and transfer their working solutions.",
    "    '''",
    "",
    "    def __init__(self):",
    "        self.task_embeddings: Dict[str, np.ndarray] = {}",
    "        self.task_solutions: Dict[str, List[Tuple[str, float]]] = {}  # task_id -> [(heuristic_name, score)]",
    "",
    "    def build_index(self, train_tasks: Dict[str, Dict]):",
    '        """Build embeddings for all training tasks and find their solutions."""',
    '        print(f"[SIM] Building similarity index for {len(train_tasks)} training tasks...")',
    "        for task_id, task in tqdm(train_tasks.items(), desc='Building index'):",
    "            self.task_embeddings[task_id] = compute_task_embedding(task)",
    "            # Find which heuristics solve this training task",
    '            pairs = task.get(\'train\', [])',
    "            solved = []",
    "            for name, fn in ALL_HEURISTICS:",
    "                score, passed, total = score_heuristic_on_training(fn, pairs)",
    "                if score >= 1.0:",
    "                    solved.append((name, score))",
    "            self.task_solutions[task_id] = solved",
    '        solved_count = sum(1 for v in self.task_solutions.values() if v)',
    '        print(f"[SIM] Index built: {len(train_tasks)} tasks, {solved_count} with heuristic solutions")',
    "",
    "    def find_similar(self, eval_task: Dict, top_k: int = 5) -> List[Tuple[str, float, List[Tuple[str, float]]]]:",
    '        """',
    "        Find top-k most similar training tasks to the eval task.",
    "        Returns list of (task_id, similarity, solved_heuristics) tuples.",
    "        '''",
    "        eval_emb = compute_task_embedding(eval_task)",
    "        similarities = []",
    "        for task_id, train_emb in self.task_embeddings.items():",
    "            sim = cosine_similarity(eval_emb, train_emb)",
    "            if sim > 0.5:  # threshold",
    "                similarities.append((task_id, sim, self.task_solutions.get(task_id, [])))",
    "        similarities.sort(key=lambda x: -x[1])",
    "        return similarities[:top_k]",
    "",
    "    def get_transfer_heuristics(self, eval_task: Dict, top_k: int = 5) -> List[Tuple[str, Callable, float]]:",
    '        """',
    "        Get heuristics that solved similar training tasks.",
    "        Returns list of (heuristic_name, fn, similarity_score).",
    "        '''",
    "        similar = self.find_similar(eval_task, top_k)",
    "        transfer = []",
    "        seen_names = set()",
    "        for task_id, sim, solutions in similar:",
    "            for hname, hscore in solutions:",
    "                if hname not in seen_names:",
    "                    # Look up the function from ALL_HEURISTICS",
    "                    for aname, afn in ALL_HEURISTICS:",
    "                        if aname == hname:",
    "                            transfer.append((hname, afn, sim))",
    "                            seen_names.add(hname)",
    "                            break",
    "        return transfer",
    "",
    "",
    "similarity_index = TaskSimilarityIndex()",
    'print("[SIM] Task similarity index initialized.")',
))

# ---- CELL 9: Object-Centric Reasoning (markdown) ----
cells.append(md_cell(
    "## Object-Centric Reasoning (NEW in v3)",
    "",
    "Decomposes grids into objects (connected components with features), matches objects",
    "between input and output, and detects consistent transformations across training pairs."
))

# ---- CELL 10: Object-Centric (code) ----
cells.append(code_cell(
    "# ============================================================================",
    "# CELL 5: Object-Centric Reasoning (NEW v3)",
    "# ============================================================================",
    "'''",
    "Object-centric reasoning: decompose grids into objects, match them across",
    "input/output pairs, and detect consistent geometric transformations.",
    "'''",
    "",
    "def analyze_objects(grid: List[List[int]]) -> List[Dict]:",
    '    """',
    "    Decompose a grid into objects with features.",
    "    Each object: {color, size, bbox, centroid, pixels}",
    "    '''",
    "    components = find_components(grid, connectivity=4)",
    "    arr = grid_to_numpy(grid)",
    "    objects = []",
    "    for comp in components:",
    "        if not comp:",
    "            continue",
    "        color = int(arr[comp[0][0], comp[0][1]])",
    "        min_r, min_c, max_r, max_c = component_bounding_box(comp)",
    "        centroid_r = sum(p[0] for p in comp) / len(comp)",
    "        centroid_c = sum(p[1] for p in comp) / len(comp)",
    "        objects.append({",
    "            'color': color,",
    "            'size': len(comp),",
    "            'bbox': (min_r, min_c, max_r, max_c),",
    "            'width': max_c - min_c + 1,",
    "            'height': max_r - min_r + 1,",
    "            'centroid': (centroid_r, centroid_c),",
    "            'pixels': set(comp),",
    "        })",
    "    return objects",
    "",
    "",
    "def match_objects(inp_objs: List[Dict], out_objs: List[Dict]) -> List[Tuple[int, int]]:",
    '    """',
    "    Match input objects to output objects by color+size.",
    "    Returns list of (inp_idx, out_idx) pairs.",
    "    '''",
    "    matches = []",
    "    used_out = set()",
    "    # Score pairs by color match + size similarity",
    "    candidates = []",
    "    for i, inp in enumerate(inp_objs):",
    "        for j, out in enumerate(out_objs):",
    "            color_match = 1.0 if inp['color'] == out['color'] else 0.0",
    "            size_ratio = min(inp['size'], out['size']) / max(inp['size'], out['size'], 1)",
    "            score = color_match * 0.7 + size_ratio * 0.3",
    "            candidates.append((score, i, j))",
    "    candidates.sort(key=lambda x: -x[0])",
    "    for score, i, j in candidates:",
    "        if i not in {m[0] for m in matches} and j not in used_out:",
    "            if score > 0.3:",
    "                matches.append((i, j))",
    "                used_out.add(j)",
    "    return matches",
    "",
    "",
    "def detect_object_transformation(inp_obj: Dict, out_obj: Dict) -> Optional[Dict]:",
    '    """',
    "    Detect transformation between a matched input/output object pair.",
    "    Returns dict with transform type and parameters, or None.",
    "    '''",
    "    transform = {}",
    "",
    "    # Color change",
    "    if inp_obj['color'] != out_obj['color']:",
    "        transform['color'] = out_obj['color']",
    "",
    "    # Scale change",
    "    if inp_obj['width'] > 0 and inp_obj['height'] > 0:",
    "        scale_h = out_obj['height'] / inp_obj['height']",
    "        scale_w = out_obj['width'] / inp_obj['width']",
    "        if abs(scale_h - round(scale_h)) < 0.1 and abs(scale_w - round(scale_w)) < 0.1:",
    "            if scale_h != 1.0 or scale_w != 1.0:",
    "                transform['scale'] = (int(round(scale_h)), int(round(scale_w)))",
    "",
    "    # Translation",
    "    dr = out_obj['centroid'][0] - inp_obj['centroid'][0]",
    "    dc = out_obj['centroid'][1] - inp_obj['centroid'][1]",
    "    if abs(dr) > 0.5 or abs(dc) > 0.5:",
    "        transform['translate'] = (int(round(dr)), int(round(dc)))",
    "",
    "    # Reshape (width/height swap or change)",
    "    if inp_obj['width'] != out_obj['width'] or inp_obj['height'] != out_obj['height']:",
    "        if 'scale' not in transform:",
    "            transform['reshape'] = (out_obj['height'], out_obj['width'])",
    "",
    "    return transform if transform else None",
    "",
    "",
    "def object_centric_solve(task: Dict) -> Optional[Callable]:",
    '    """',
    "    Try to solve a task using object-centric reasoning.",
    "    Detects a consistent transformation across ALL training pairs.",
    "    Returns a transform function if found, else None.",
    "    '''",
    '    pairs = task.get(\'train\', [])',
    "    if len(pairs) < 2:",
    "        return None",
    "",
    "    all_transforms = []",
    "    for pair in pairs:",
    "        inp_objs = analyze_objects(pair['input'])",
    "        out_objs = analyze_objects(pair['output'])",
    "        if not inp_objs or not out_objs:",
    "            return None",
    "        matches = match_objects(inp_objs, out_objs)",
    "        if not matches:",
    "            return None",
    "        pair_transforms = []",
    "        for i_idx, o_idx in matches:",
    "            t = detect_object_transformation(inp_objs[i_idx], out_objs[o_idx])",
    "            if t:",
    "                pair_transforms.append(t)",
    "        if not pair_transforms:",
    "            return None",
    "        all_transforms.append(pair_transforms)",
    "",
    "    # Check if all pairs have the same transformation pattern",
    "    if len(all_transforms) < 2:",
    "        return None",
    "",
    "    # Find the most common transformation keys",
    "    key_sets = [set(t.keys()) for ts in all_transforms for t in ts]",
    "    if not key_sets:",
    "        return None",
    "",
    "    # Check for consistent color transformation",
    "    color_transforms = []",
    "    for pair_ts in all_transforms:",
    "        for t in pair_ts:",
    "            if 'color' in t:",
    "                color_transforms.append(t['color'])",
    "    if color_transforms:",
    "        if len(set(color_transforms)) == 1:",
    "            new_color = color_transforms[0]",
    "            def make_color_fn(c):",
    "                def fn(grid):",
    "                    g = grid_to_numpy(grid)",
    "                    return np.where(g > 0, c, 0).tolist()",
    "                return fn",
    "            return make_color_fn(new_color)",
    "",
    "    # Check for consistent translation",
    "    trans_transforms = []",
    "    for pair_ts in all_transforms:",
    "        for t in pair_ts:",
    "            if 'translate' in t:",
    "                trans_transforms.append(t['translate'])",
    "    if len(trans_transforms) >= 2 and len(set(trans_transforms)) == 1:",
    "        dr, dc = trans_transforms[0]",
    "        def make_translate_fn(dr, dc):",
    "            def fn(grid):",
    "                g = grid_to_numpy(grid)",
    "                h, w = g.shape",
    "                out = np.zeros_like(g)",
    "                for r in range(h):",
    "                    for c in range(w):",
    "                        nr, nc = r + dr, c + dc",
    "                        if 0 <= nr < h and 0 <= nc < w:",
    "                            out[nr, nc] = g[r, c]",
    "                return out.tolist()",
    "            return fn",
    "        return make_translate_fn(dr, dc)",
    "",
    "    # Check for consistent scale",
    "    scale_transforms = []",
    "    for pair_ts in all_transforms:",
    "        for t in pair_ts:",
    "            if 'scale' in t:",
    "                scale_transforms.append(t['scale'])",
    "    if len(scale_transforms) >= 2 and len(set(scale_transforms)) == 1:",
    "        sh, sw = scale_transforms[0]",
    "        def make_scale_fn(sh, sw):",
    "            def fn(grid):",
    "                g = grid_to_numpy(grid)",
    "                return np.repeat(np.repeat(g, sh, axis=0), sw, axis=1).tolist()",
    "            return fn",
    "        return make_scale_fn(sh, sw)",
    "",
    "    return None",
    "",
    "",
    'print("[OBJECT] Object-centric reasoning module loaded.")',
))

print("Cells 1-10 built. Continuing with cells 11-18...")
# Save progress indicator
with open("/tmp/v3_build_progress.txt", "w") as f:
    f.write("phase1_done")
