#!/usr/bin/env python3
"""Generate ARC-AGI-2 Solver v3 notebook - Part 2 (remaining cells)."""

import json

def L(*lines):
    result = []
    for i, line in enumerate(lines):
        if i < len(lines) - 1:
            result.append(line + "\n")
        else:
            result.append(line)
    return result

def md_cell(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": L(*lines)}

def code_cell(*lines):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": L(*lines)}

# Load part 1
with open("/tmp/v3_cells_part1.json") as f:
    cells = json.load(f)

###############################################################################
# CELL 11: Expanded Heuristic Library (markdown)
###############################################################################
cells.append(md_cell(
    "## Expanded Heuristic Library (70+ Solvers)\n",
    "\n",
    "All v2 base heuristics (38) plus new morphological, sorting, compression,\n",
    "tile detection, distribution, and 30+ additional composite solvers.\n",
))

###############################################################################
# CELL 12: All heuristic functions + registration + scoring (code)
###############################################################################
cells.append(code_cell(
    "# ============================================================================\n",
    "# CELL 6: Expanded Heuristic Library (70+ Solvers)\n",
    "# ============================================================================\n",
    "'''\n",
    "70+ heuristic solvers organized by category.\n",
    "Each solver is a function: grid -> grid (or raises on failure).\n",
    "'''\n",
    "\n",
    "# === GEOMETRIC SOLVERS (1-8) =========================================\n",
    "\n",
    "def h_identity(grid):\n",
    "    return copy.deepcopy(grid)\n",
    "\n",
    "def h_rotate90(grid):\n",
    "    return np.rot90(grid_to_numpy(grid), 1).tolist()\n",
    "\n",
    "def h_rotate180(grid):\n",
    "    return np.rot90(grid_to_numpy(grid), 2).tolist()\n",
    "\n",
    "def h_rotate270(grid):\n",
    "    return np.rot90(grid_to_numpy(grid), 3).tolist()\n",
    "\n",
    "def h_flip_h(grid):\n",
    "    g = grid_to_numpy(grid)\n",
    "    return g[:, ::-1].tolist()\n",
    "\n",
    "def h_flip_v(grid):\n",
    "    g = grid_to_numpy(grid)\n",
    "    return g[::-1, :].tolist()\n",
    "\n",
    "def h_flip_diag(grid):\n",
    "    g = grid_to_numpy(grid)\n",
    "    return g.T.tolist()\n",
    "\n",
    "def h_flip_anti_diag(grid):\n",
    "    g = grid_to_numpy(grid)\n",
    "    return np.rot90(g.T).tolist()\n",
    "\n",
    "\n",
    "# === COLOR SOLVERS (9-16) ==============================================\n",
    "\n",
    "def h_color_complement(grid):\n",
    "    g = grid_to_numpy(grid)\n",
    "    return (9 - g).tolist()\n",
    "\n",
    "def h_color_add_k(grid, k=1):\n",
    "    g = grid_to_numpy(grid)\n",
    "    return ((g + k) % 10).tolist()\n",
    "\n",
    "def h_color_sub_k(grid, k=1):\n",
    "    g = grid_to_numpy(grid)\n",
    "    return ((g - k) % 10).tolist()\n",
    "\n",
    "def h_fill_most_common(grid):\n",
    "    g = grid_to_numpy(grid)\n",
    "    vals = g[g > 0].tolist()\n",
    "    if not vals:\n",
    "        return copy.deepcopy(grid)\n",
    "    mc = Counter(int(v) for v in vals).most_common(1)[0][0]\n",
    "    return np.where(g > 0, mc, 0).tolist()\n",
    "\n",
    "def h_extract_color(grid, color=1):\n",
    "    g = grid_to_numpy(grid)\n",
    "    return np.where(g == color, color, 0).tolist()\n",
    "\n",
    "def h_remap_colors(grid):\n",
    "    g = grid_to_numpy(grid)\n",
    "    unique = []\n",
    "    mapping = {}\n",
    "    for val in g.flatten():\n",
    "        v = int(val)\n",
    "        if v not in mapping:\n",
    "            if v == 0:\n",
    "                mapping[v] = 0\n",
    "            else:\n",
    "                mapping[v] = len(unique) + 1\n",
    "                unique.append(v)\n",
    "    result = np.zeros_like(g)\n",
    "    for v, new_v in mapping.items():\n",
    "        result[g == v] = new_v\n",
    "    return result.tolist()\n",
    "\n",
    "def h_count_colors_output(grid):\n",
    "    g = grid_to_numpy(grid)\n",
    "    colors = sorted(set(int(c) for c in g.flatten() if c != 0))\n",
    "    if not colors:\n",
    "        return [[0]]\n",
    "    counts = [int(np.sum(g == c)) for c in colors]\n",
    "    return [counts]\n",
    "\n",
    "def h_invert_colors(grid):\n",
    "    g = grid_to_numpy(grid)\n",
    "    unique = sorted(set(int(c) for c in g.flatten() if c != 0))\n",
    "    if len(unique) <= 1:\n",
    "        return copy.deepcopy(grid)\n",
    "    mapping = {0: 0}\n",
    "    for i, v in enumerate(unique):\n",
    "        mapping[v] = unique[(i + 1) % len(unique)]\n",
    "    result = np.zeros_like(g)\n",
    "    for old, new in mapping.items():\n",
    "        result[g == old] = new\n",
    "    return result.tolist()\n",
    "\n",
    "\n",
    "# === NEW v3 COLOR SOLVERS ==============================================\n",
    "\n",
    "def h_swap_colors(grid, c1=1, c2=2):\n",
    "    '''Swap two colors in the grid.'''\n",
    "    g = grid_to_numpy(grid)\n",
    "    mask1 = (g == c1)\n",
    "    mask2 = (g == c2)\n",
    "    g[mask1] = c2\n",
    "    g[mask2] = c1\n",
    "    return g.tolist()\n",
    "\n",
    "def h_replace_color(grid, old=1, new=2):\n",
    "    '''Replace one color with another.'''\n",
    "    g = grid_to_numpy(grid)\n",
    "    return np.where(g == old, new, g).tolist()\n",
    "\n",
    "\n",
    "# === OBJECT SOLVERS (17-22) ============================================\n",
    "\n",
    "def h_crop(grid):\n",
    "    g = grid_to_numpy(grid)\n",
    "    if g.size == 0:\n",
    "        return grid\n",
    "    rows_nz = np.where(g.any(axis=1))[0]\n",
    "    cols_nz = np.where(g.any(axis=0))[0]\n",
    "    if len(rows_nz) == 0 or len(cols_nz) == 0:\n",
    "        return [[0]]\n",
    "    return g[rows_nz[0]:rows_nz[-1]+1, cols_nz[0]:cols_nz[-1]+1].tolist()\n",
    "\n",
    "def h_crop_each_color(grid):\n",
    "    g = grid_to_numpy(grid)\n",
    "    colors = sorted(set(int(c) for c in g.flatten() if c != 0))\n",
    "    if not colors:\n",
    "        return [[0]]\n",
    "    sub_grids = []\n",
    "    max_h = 0\n",
    "    for c in colors:\n",
    "        mask = (g == c).astype(int)\n",
    "        rows_nz = np.where(mask.any(axis=1))[0]\n",
    "        cols_nz = np.where(mask.any(axis=0))[0]\n",
    "        if len(rows_nz) == 0:\n",
    "            continue\n",
    "        sub = mask[rows_nz[0]:rows_nz[-1]+1, cols_nz[0]:cols_nz[-1]+1]\n",
    "        sub_grids.append(sub)\n",
    "        max_h = max(max_h, sub.shape[0])\n",
    "    if not sub_grids:\n",
    "        return [[0]]\n",
    "    padded = []\n",
    "    for sg in sub_grids:\n",
    "        if sg.shape[0] < max_h:\n",
    "            pad = np.zeros((max_h - sg.shape[0], sg.shape[1]), dtype=int)\n",
    "            sg = np.vstack([sg, pad])\n",
    "        padded.append(sg)\n",
    "    return np.hstack(padded).tolist()\n",
    "\n",
    "def h_extract_largest_component(grid):\n",
    "    comps = find_components(grid, 4)\n",
    "    if not comps:\n",
    "        return [[0] * len(grid[0]) for _ in range(len(grid))]\n",
    "    largest = max(comps, key=len)\n",
    "    g = np.zeros_like(grid_to_numpy(grid))\n",
    "    color = int(grid_to_numpy(grid)[largest[0][0], largest[0][1]])\n",
    "    for r, c in largest:\n",
    "        g[r, c] = color\n",
    "    return g.tolist()\n",
    "\n",
    "def h_extract_smallest_component(grid):\n",
    "    comps = find_components(grid, 4)\n",
    "    if not comps:\n",
    "        return [[0] * len(grid[0]) for _ in range(len(grid))]\n",
    "    smallest = min(comps, key=len)\n",
    "    g = np.zeros_like(grid_to_numpy(grid))\n",
    "    color = int(grid_to_numpy(grid)[smallest[0][0], smallest[0][1]])\n",
    "    for r, c in smallest:\n",
    "        g[r, c] = color\n",
    "    return g.tolist()\n",
    "\n",
    "def h_move_to_topleft(grid):\n",
    "    return h_crop(grid)\n",
    "\n",
    "def h_extract_all_components_separate(grid):\n",
    "    return h_extract_largest_component(grid)\n",
    "\n",
    "\n",
    "# === SCALING SOLVERS (23-26) ===========================================\n",
    "\n",
    "def h_scale_2x(grid):\n",
    "    g = grid_to_numpy(grid)\n",
    "    return np.repeat(np.repeat(g, 2, axis=0), 2, axis=1).tolist()\n",
    "\n",
    "def h_scale_3x(grid):\n",
    "    g = grid_to_numpy(grid)\n",
    "    return np.repeat(np.repeat(g, 3, axis=0), 3, axis=1).tolist()\n",
    "\n",
    "def h_shrink_by_half(grid):\n",
    "    g = grid_to_numpy(grid)\n",
    "    if g.shape[0] < 2 or g.shape[1] < 2:\n",
    "        return copy.deepcopy(grid)\n",
    "    return g[::2, ::2].tolist()\n",
    "\n",
    "def h_shrink_by_third(grid):\n",
    "    g = grid_to_numpy(grid)\n",
    "    if g.shape[0] < 3 or g.shape[1] < 3:\n",
    "        return copy.deepcopy(grid)\n",
    "    return g[::3, ::3].tolist()\n",
    "\n",
    "\n",
    "# === TILING SOLVERS (27-30) ============================================\n",
    "\n",
    "def h_tile_2x2(grid):\n",
    "    g = grid_to_numpy(grid)\n",
    "    return np.tile(g, (2, 2)).tolist()\n",
    "\n",
    "def h_tile_3x3(grid):\n",
    "    g = grid_to_numpy(grid)\n",
    "    return np.tile(g, (3, 3)).tolist()\n",
    "\n",
    "def h_repeat_h(grid):\n",
    "    g = grid_to_numpy(grid)\n",
    "    return np.tile(g, (1, 2)).tolist()\n",
    "\n",
    "def h_repeat_v(grid):\n",
    "    g = grid_to_numpy(grid)\n",
    "    return np.tile(g, (2, 1)).tolist()\n",
    "\n",
    "\n",
    "# === PATTERN SOLVERS (31-34) ===========================================\n",
    "\n",
    "def h_mirror_h_full(grid):\n",
    "    g = grid_to_numpy(grid)\n",
    "    return np.hstack([g, g[:, ::-1]]).tolist()\n",
    "\n",
    "def h_mirror_v_full(grid):\n",
    "    g = grid_to_numpy(grid)\n",
    "    return np.vstack([g, g[::-1, :]]).tolist()\n",
    "\n",
    "def h_mirror_4way(grid):\n",
    "    g = grid_to_numpy(grid)\n",
    "    top = np.hstack([g, g[:, ::-1]])\n",
    "    return np.vstack([top, top[::-1, :]]).tolist()\n",
    "\n",
    "def h_extract_border(grid):\n",
    "    g = grid_to_numpy(grid).copy()\n",
    "    if g.shape[0] > 2 and g.shape[1] > 2:\n",
    "        g[1:-1, 1:-1] = 0\n",
    "    return g.tolist()\n",
    "\n",
    "\n",
    "# === LOGIC / CONDITIONAL SOLVERS (35-38) ===============================\n",
    "\n",
    "def h_conditional_color_density(grid):\n",
    "    g = grid_to_numpy(grid)\n",
    "    density = np.sum(g != 0) / max(g.size, 1)\n",
    "    if density > 0.5:\n",
    "        return (9 - g).tolist()\n",
    "    return copy.deepcopy(grid)\n",
    "\n",
    "def h_conditional_size_rotate(grid):\n",
    "    g = grid_to_numpy(grid)\n",
    "    h, w = g.shape\n",
    "    if h == w:\n",
    "        return np.rot90(g, 1).tolist()\n",
    "    elif w > h:\n",
    "        return g[:, ::-1].tolist()\n",
    "    else:\n",
    "        return g[::-1, :].tolist()\n",
    "\n",
    "def h_threshold_binary(grid):\n",
    "    g = grid_to_numpy(grid)\n",
    "    return (g > 0).astype(int).tolist()\n",
    "\n",
    "def h_replace_zero_with_dominant(grid):\n",
    "    g = grid_to_numpy(grid)\n",
    "    colors = Counter(int(v) for v in g.flatten())\n",
    "    if colors:\n",
    "        dominant = colors.most_common(1)[0][0]\n",
    "        return np.where(g == 0, dominant, g).tolist()\n",
    "    return copy.deepcopy(grid)\n",
    "\n",
    "\n",
    "# ==========================================================================\n",
    "# NEW v3 HEURISTICS (39+)\n",
    "# ==========================================================================\n",
    "\n",
    "# --- Morphological ---\n",
    "\n",
    "def h_dilate(grid):\n",
    "    '''Morphological dilation: expand non-zero cells by 1 pixel.'''\n",
    "    g = grid_to_numpy(grid).copy()\n",
    "    mask = (g > 0)\n",
    "    h, w = g.shape\n",
    "    dilated = mask.copy()\n",
    "    for r in range(h):\n",
    "        for c in range(w):\n",
    "            if mask[r, c]:\n",
    "                for dr, dc in [(-1,0),(1,0),(0,-1),(0,1)]:\n",
    "                    nr, nc = r+dr, c+dc\n",
    "                    if 0 <= nr < h and 0 <= nc < w:\n",
    "                        dilated[nr, nc] = True\n",
    "    result = np.zeros_like(g)\n",
    "    result[dilated] = g[mask].max() if mask.any() else 1\n",
    "    return result.tolist()\n",
    "\n",
    "def h_erode(grid):\n",
    "    '''Morphological erosion: shrink non-zero cells by 1 pixel.'''\n",
    "    g = grid_to_numpy(grid)\n",
    "    h, w = g.shape\n",
    "    mask = (g > 0)\n",
    "    eroded = np.zeros_like(g, dtype=bool)\n",
    "    for r in range(h):\n",
    "        for c in range(w):\n",
    "            if mask[r, c]:\n",
    "                all_nbrs = True\n",
    "                for dr, dc in [(-1,0),(1,0),(0,-1),(0,1)]:\n",
    "                    nr, nc = r+dr, c+dc\n",
    "                    if 0 <= nr < h and 0 <= nc < w:\n",
    "                        if not mask[nr, nc]:\n",
    "                            all_nbrs = False\n",
    "                            break\n",
    "                if all_nbrs:\n",
    "                    eroded[r, c] = True\n",
    "    result = np.zeros_like(g)\n",
    "    result[eroded] = g[mask].max() if mask.any() else 1\n",
    "    return result.tolist()\n",
    "\n",
    "def h_outline_objects(grid):\n",
    "    '''Extract borders/edges of objects only.'''\n",
    "    g = grid_to_numpy(grid)\n",
    "    h, w = g.shape\n",
    "    mask = (g > 0)\n",
    "    outline = np.zeros_like(g)\n",
    "    for r in range(h):\n",
    "        for c in range(w):\n",
    "            if mask[r, c]:\n",
    "                is_border = False\n",
    "                for dr, dc in [(-1,0),(1,0),(0,-1),(0,1)]:\n",
    "                    nr, nc = r+dr, c+dc\n",
    "                    if nr < 0 or nr >= h or nc < 0 or nc >= w or not mask[nr, nc]:\n",
    "                        is_border = True\n",
    "                        break\n",
    "                if is_border:\n",
    "                    outline[r, c] = g[r, c]\n",
    "    return outline.tolist()\n",
    "\n",
    "def h_fill_enclosed(grid):\n",
    "    '''Flood-fill enclosed 0-regions with the surrounding color.'''\n",
    "    g = grid_to_numpy(grid)\n",
    "    h, w = g.shape\n",
    "    if h < 3 or w < 3:\n",
    "        return copy.deepcopy(grid)\n",
    "    visited = np.zeros((h, w), dtype=bool)\n",
    "    q = deque()\n",
    "    # Add all border zeros to queue\n",
    "    for r in range(h):\n",
    "        for c in range(w):\n",
    "            if (r == 0 or r == h-1 or c == 0 or c == w-1) and g[r, c] == 0:\n",
    "                q.append((r, c))\n",
    "                visited[r, c] = True\n",
    "    # BFS from border zeros\n",
    "    while q:\n",
    "        r, c = q.popleft()\n",
    "        for dr, dc in [(-1,0),(1,0),(0,-1),(0,1)]:\n",
    "            nr, nc = r+dr, c+dc\n",
    "            if 0 <= nr < h and 0 <= nc < w and not visited[nr, nc] and g[nr, nc] == 0:\n",
    "                visited[nr, nc] = True\n",
    "                q.append((nr, nc))\n",
    "    # Any unvisited zero is enclosed - fill with most common non-zero color\n",
    "    nonzero_vals = g[g > 0]\n",
    "    if len(nonzero_vals) == 0:\n",
    "        return copy.deepcopy(grid)\n",
    "    fill_color = int(Counter(nonzero_vals.tolist()).most_common(1)[0][0])\n",
    "    result = g.copy()\n",
    "    for r in range(h):\n",
    "        for c in range(w):\n",
    "            if g[r, c] == 0 and not visited[r, c]:\n",
    "                result[r, c] = fill_color\n",
    "    return result.tolist()\n",
    "\n",
    "\n",
    "# --- Sorting ---\n",
    "\n",
    "def h_sort_rows_by_sum(grid):\n",
    "    '''Sort rows by their sum (ascending).'''\n",
    "    g = grid_to_numpy(grid)\n",
    "    row_sums = g.sum(axis=1)\n",
    "    order = np.argsort(row_sums)\n",
    "    return g[order].tolist()\n",
    "\n",
    "def h_sort_cols_by_sum(grid):\n",
    "    '''Sort columns by their sum (ascending).'''\n",
    "    g = grid_to_numpy(grid)\n",
    "    col_sums = g.sum(axis=0)\n",
    "    order = np.argsort(col_sums)\n",
    "    return g[:, order].tolist()\n",
    "\n",
    "def h_sort_rows_by_unique(grid):\n",
    "    '''Sort rows by number of unique values.'''\n",
    "    g = grid_to_numpy(grid)\n",
    "    unique_counts = np.array([len(set(row)) for row in g])\n",
    "    order = np.argsort(unique_counts)\n",
    "    return g[order].tolist()\n",
    "\n",
    "def h_sort_cols_by_unique(grid):\n",
    "    '''Sort columns by number of unique values.'''\n",
    "    g = grid_to_numpy(grid)\n",
    "    unique_counts = np.array([len(set(g[:, c])) for c in range(g.shape[1])])\n",
    "    order = np.argsort(unique_counts)\n",
    "    return g[:, order].tolist()\n",
    "\n",
    "\n",
    "# --- Compression / Extraction ---\n",
    "\n",
    "def h_compress_rows(grid):\n",
    "    '''Remove all-zero rows.'''\n",
    "    g = grid_to_numpy(grid)\n",
    "    mask = g.any(axis=1)\n",
    "    if not mask.any():\n",
    "        return [[0]]\n",
    "    return g[mask].tolist()\n",
    "\n",
    "def h_compress_cols(grid):\n",
    "    '''Remove all-zero columns.'''\n",
    "    g = grid_to_numpy(grid)\n",
    "    mask = g.any(axis=0)\n",
    "    if not mask.any():\n",
    "        return [[0]]\n",
    "    return g[:, mask].tolist()\n",
    "\n",
    "def h_extract_nonzero_rows(grid):\n",
    "    '''Same as compress_rows.'''\n",
    "    return h_compress_rows(grid)\n",
    "\n",
    "def h_extract_nonzero_cols(grid):\n",
    "    '''Same as compress_cols.'''\n",
    "    return h_compress_cols(grid)\n",
    "\n",
    "def h_remove_duplicate_rows(grid):\n",
    "    '''Remove duplicate rows, keeping first occurrence.'''\n",
    "    g = grid_to_numpy(grid)\n",
    "    seen = set()\n",
    "    result = []\n",
    "    for row in g:\n",
    "        key = tuple(row.tolist())\n",
    "        if key not in seen:\n",
    "            seen.add(key)\n",
    "            result.append(row)\n",
    "    if not result:\n",
    "        return [[0]]\n",
    "    return np.array(result).tolist()\n",
    "\n",
    "def h_remove_duplicate_cols(grid):\n",
    "    '''Remove duplicate columns, keeping first occurrence.'''\n",
    "    g = grid_to_numpy(grid)\n",
    "    seen = set()\n",
    "    keep = []\n",
    "    for c in range(g.shape[1]):\n",
    "        key = tuple(g[:, c].tolist())\n",
    "        if key not in seen:\n",
    "            seen.add(key)\n",
    "            keep.append(c)\n",
    "    if not keep:\n",
    "        return [[0]]\n",
    "    return g[:, keep].tolist()\n",
    "\n",
    "\n",
    "# --- Object Manipulation ---\n",
    "\n",
    "def h_stack_objects_vertically(grid):\n",
    "    '''Crop each component and stack vertically.'''\n",
    "    comps = find_components(grid, 4)\n",
    "    if not comps:\n",
    "        return [[0]]\n",
    "    arr = grid_to_numpy(grid)\n",
    "    parts = []\n",
    "    for comp in sorted(comps, key=lambda c: component_bounding_box(c)[0]):\n",
    "        min_r, min_c, max_r, max_c = component_bounding_box(comp)\n",
    "        parts.append(arr[min_r:max_r+1, min_c:max_c+1])\n",
    "    return np.vstack(parts).tolist()\n",
    "\n",
    "def h_stack_objects_horizontally(grid):\n",
    "    '''Crop each component and stack horizontally.'''\n",
    "    comps = find_components(grid, 4)\n",
    "    if not comps:\n",
    "        return [[0]]\n",
    "    arr = grid_to_numpy(grid)\n",
    "    parts = []\n",
    "    max_h = 0\n",
    "    for comp in sorted(comps, key=lambda c: component_bounding_box(c)[1]):\n",
    "        min_r, min_c, max_r, max_c = component_bounding_box(comp)\n",
    "        parts.append(arr[min_r:max_r+1, min_c:max_c+1])\n",
    "        max_h = max(max_h, max_r - min_r + 1)\n",
    "    padded = []\n",
    "    for p in parts:\n",
    "        if p.shape[0] < max_h:\n",
    "            pad = np.zeros((max_h - p.shape[0], p.shape[1]), dtype=int)\n",
    "            p = np.vstack([p, pad])\n",
    "        padded.append(p)\n",
    "    return np.hstack(padded).tolist()\n",
    "\n",
    "def h_interleave_rows(grid):\n",
    "    '''Interleave rows from top and bottom halves.'''\n",
    "    g = grid_to_numpy(grid)\n",
    "    h, w = g.shape\n",
    "    if h < 2:\n",
    "        return copy.deepcopy(grid)\n",
    "    top = g[:h//2]\n",
    "    bot = g[h//2:]\n",
    "    result = []\n",
    "    for i in range(max(len(top), len(bot))):\n",
    "        if i < len(top):\n",
    "            result.append(top[i])\n",
    "        if i < len(bot):\n",
    "            result.append(bot[i])\n",
    "    return np.array(result).tolist()\n",
    "\n",
    "def h_interleave_cols(grid):\n",
    "    '''Interleave columns from left and right halves.'''\n",
    "    g = grid_to_numpy(grid)\n",
    "    h, w = g.shape\n",
    "    if w < 2:\n",
    "        return copy.deepcopy(grid)\n",
    "    left = g[:, :w//2]\n",
    "    right = g[:, w//2:]\n",
    "    cols = []\n",
    "    for i in range(max(left.shape[1], right.shape[1])):\n",
    "        if i < left.shape[1]:\n",
    "            cols.append(left[:, i])\n",
    "        if i < right.shape[1]:\n",
    "            cols.append(right[:, i])\n",
    "    return np.column_stack(cols).tolist()\n",
    "\n",
    "def h_grow_objects(grid):\n",
    "    '''Grow each object by 1 pixel (same as dilate).'''\n",
    "    return h_dilate(grid)\n",
    "\n",
    "def h_shrink_objects(grid):\n",
    "    '''Shrink each object by 1 pixel (same as erode).'''\n",
    "    return h_erode(grid)\n",
    "\n",
    "def h_center_objects(grid):\n",
    "    '''Center each object in its bounding box.'''\n",
    "    g = grid_to_numpy(grid)\n",
    "    h, w = g.shape\n",
    "    min_r, min_c, max_r, max_c = 0, 0, h-1, w-1\n",
    "    rows_nz = np.where(g.any(axis=1))[0]\n",
    "    cols_nz = np.where(g.any(axis=0))[0]\n",
    "    if len(rows_nz) == 0 or len(cols_nz) == 0:\n",
    "        return copy.deepcopy(grid)\n",
    "    content = g[rows_nz[0]:rows_nz[-1]+1, cols_nz[0]:cols_nz[-1]+1]\n",
    "    ch, cw = content.shape\n",
    "    # Already centered since we crop to content\n",
    "    return content.tolist()\n",
    "\n",
    "\n",
    "# --- Translation / Extraction ---\n",
    "\n",
    "def h_translate_content(grid, dr=0, dc=0):\n",
    "    '''Translate all content by (dr, dc) pixels.'''\n",
    "    g = grid_to_numpy(grid)\n",
    "    h, w = g.shape\n",
    "    out = np.zeros_like(g)\n",
    "    for r in range(h):\n",
    "        for c in range(w):\n",
    "            nr, nc = r + dr, c + dc\n",
    "            if 0 <= nr < h and 0 <= nc < w:\n",
    "                out[nr, nc] = g[r, c]\n",
    "    return out.tolist()\n",
    "\n",
    "def h_extract_diagonal(grid):\n",
    "    '''Extract main diagonal as a column vector.'''\n",
    "    g = grid_to_numpy(grid)\n",
    "    n = min(g.shape[0], g.shape[1])\n",
    "    diag = g[:n, :n].diagonal().reshape(-1, 1)\n",
    "    return diag.tolist()\n",
    "\n",
    "def h_extract_anti_diagonal(grid):\n",
    "    '''Extract anti-diagonal as a column vector.'''\n",
    "    g = grid_to_numpy(grid)\n",
    "    n = min(g.shape[0], g.shape[1])\n",
    "    anti_diag = g[:n, :n][:, ::-1].diagonal().reshape(-1, 1)\n",
    "    return anti_diag.tolist()\n",
    "\n",
    "\n",
    "# --- Rolling Pattern / Tile Detection ---\n",
    "\n",
    "def h_detect_and_extract_tile(grid):\n",
    "    '''Detect repeating tile pattern and extract the base tile.'''\n",
    "    g = grid_to_numpy(grid)\n",
    "    h, w = g.shape\n",
    "    # Try different tile sizes\n",
    "    for th in range(1, h // 2 + 1):\n",
    "        if h % th != 0:\n",
    "            continue\n",
    "        for tw in range(1, w // 2 + 1):\n",
    "            if w % tw != 0:\n",
    "                continue\n",
    "            tile = g[:th, :tw]\n",
    "            tiled = np.tile(tile, (h // th, w // tw))\n",
    "            if np.array_equal(tiled, g):\n",
    "                return tile.tolist()\n",
    "    return copy.deepcopy(grid)\n",
    "\n",
    "def h_rolling_pattern_h(grid):\n",
    "    '''Detect horizontal rolling/repeating pattern and output single period.'''\n",
    "    g = grid_to_numpy(grid)\n",
    "    h, w = g.shape\n",
    "    for period in range(1, w // 2 + 1):\n",
    "        if w % period != 0:\n",
    "            continue\n",
    "        pattern = g[:, :period]\n",
    "        tiled = np.tile(pattern, (1, w // period))\n",
    "        if np.array_equal(tiled, g):\n",
    "            return pattern.tolist()\n",
    "    return copy.deepcopy(grid)\n",
    "\n",
    "def h_rolling_pattern_v(grid):\n",
    "    '''Detect vertical rolling/repeating pattern and output single period.'''\n",
    "    g = grid_to_numpy(grid)\n",
    "    h, w = g.shape\n",
    "    for period in range(1, h // 2 + 1):\n",
    "        if h % period != 0:\n",
    "            continue\n",
    "        pattern = g[:period, :]\n",
    "        tiled = np.tile(pattern, (h // period, 1))\n",
    "        if np.array_equal(tiled, g):\n",
    "            return pattern.tolist()\n",
    "    return copy.deepcopy(grid)\n",
    "\n",
    "\n",
    "# --- Distribution ---\n",
    "\n",
    "def h_distribute_evenly(grid):\n",
    "    '''Distribute non-zero cells evenly across the grid.'''\n",
    "    g = grid_to_numpy(grid)\n",
    "    h, w = g.shape\n",
    "    vals = g[g > 0].tolist()\n",
    "    if not vals:\n",
    "        return copy.deepcopy(grid)\n",
    "    result = np.zeros_like(g)\n",
    "    positions = list(itertools_product(range(h), range(w)))\n",
    "    random.seed(42)\n",
    "    random.shuffle(positions)\n",
    "    for i, val in enumerate(vals):\n",
    "        r, c = positions[i % len(positions)]\n",
    "        result[r, c] = val\n",
    "    return result.tolist()\n",
    "\n",
    "\n",
    "print('[HEURISTICS] 38 base + 22 new v3 heuristics defined.')\n",
))

print(f"Generated {len(cells)} cells so far (through CELL 12 heuristics)...")
with open("/tmp/v3_cells_part2.json", "w") as f:
    json.dump(cells, f)
print("Part 2 saved to /tmp/v3_cells_part2.json")
