#!/usr/bin/env python3
"""Generate ARC-AGI-2 Solver v3 notebook - Part 4 (final cells 17-20)."""

import json

def L(*lines):
    result = []
    for i, line in enumerate(lines):
        if i < len(lines) - 1:
            result.append(line + "\n")
        else:
            result.append(line)
    return result

def md_cell(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": L(*lines)}

def code_cell(*lines):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": L(*lines)}

with open("/tmp/v3_cells_part3.json") as f:
    cells = json.load(f)

###############################################################################
# CELL 17: Tiered Ensemble Solver (markdown)
###############################################################################
cells.append(md_cell(
    "## Tiered Ensemble Solver\n",
    "\n",
    "Orchestrates all solving strategies in a priority order:\n",
    "\n",
    "1. **Heuristics** (70+ solvers) \u2192 if 100% match, use it\n",
    "2. **Object-centric reasoning** \u2192 consistent transform detection\n",
    "3. **Similarity-based transfer** \u2192 use heuristics from similar training tasks\n",
    "4. **LLM self-consistency** \u2192 3 candidates at T=0.2, 0.4, 0.6\n",
    "5. **Evolutionary synthesis** \u2192 mutate/cross-over LLM candidates\n",
    "6. **Test-time LoRA training** \u2192 last resort PEFT fine-tuning\n",
    "\n",
    "Final step: pick top-2 distinct predictions for submission.\n",
))

###############################################################################
# CELL 18: solve_task() with tiered strategy + solve_all()
###############################################################################
solver_lines = [
    "# ============================================================================",
    "# CELL 10: Tiered Ensemble Solver & Main Pipeline",
    "# ============================================================================",
    "'''",
    "Tiered ensemble solver that orchestrates all strategies in priority order.",
    "'''",
    "",
    "def _apply_fn_safe(fn, grid) -> Optional[List[List[int]]]:",
    "    '''Apply a function safely, returning normalized grid or None.'''",
    "    try:",
    "        result = fn(copy.deepcopy(grid))",
    "        return normalize_grid(result)",
    "    except Exception:",
    "        return None",
    "",
    "",
    "def _zero_grid_fallback(input_grid: List[List[int]]) -> List[List[int]]:",
    "    '''Last-resort fallback: return same-size zero grid.'''",
    "    rows = len(input_grid)",
    "    cols = len(input_grid[0]) if input_grid else 0",
    "    return [[0] * cols for _ in range(rows)]",
    "",
    "",
    "def solve_task(",
    "    task: Dict,",
    "    engine: LLMEngine,",
    "    test_input_idx: int = 0,",
    "    task_id: str = '',",
    "    sim_index: Optional['TaskSimilarityIndex'] = None,",
    ") -> Tuple[List[List[List[int]]], Dict[str, Any]]:",
    "    '''",
    "    Solve a single task using the full tiered ensemble pipeline.",
    "    Returns (candidates, stats).",
    "    '''",
    "    stats = {",
    "        'task_id': task_id,",
    "        'heuristic_best_score': 0.0,",
    "        'llm_candidates': 0,",
    "        'evolved_candidates': 0,",
    "        'object_solve': False,",
    "        'similarity_transfer': False,",
    "        'lora_used': False,",
    "        'total_candidates': 0,",
    "        'strategy': 'none',",
    "    }",
    "",
    "    train_pairs = task['train']",
    '    test_input = task["test"][test_input_idx]["input"]',
    "    all_candidates: List[Tuple[List[List[int]], float, str]] = []",
    "",
    "    # =========================================================================",
    "    # TIER 1: Fast Heuristic Solvers",
    "    # =========================================================================",
    "    best_heuristics = find_best_heuristics(train_pairs, min_score=1.0, max_results=5)",
    "",
    "    if best_heuristics:",
    "        best_score = best_heuristics[0][2]",
    "        stats['heuristic_best_score'] = best_score",
    "        stats['strategy'] = 'heuristic'",
    "        for name, fn, score, passed, total in best_heuristics:",
    "            result = _apply_fn_safe(fn, test_input)",
    "            if result is not None:",
    "                all_candidates.append((result, score, f'heuristic:{name}'))",
    "        partial = find_best_partial_heuristics(train_pairs, max_results=3)",
    "        for name, fn, score, passed, total in partial:",
    "            if score < 1.0:",
    "                result = _apply_fn_safe(fn, test_input)",
    "                if result is not None:",
    "                    all_candidates.append((result, score, f'heuristic_partial:{name}'))",
    "",
    "    # =========================================================================",
    "    # TIER 2: Object-Centric Reasoning",
    "    # =========================================================================",
    "    if stats['heuristic_best_score'] < 1.0:",
    "        obj_fn = object_centric_solve(task)",
    "        if obj_fn is not None:",
    "            score, passed, total = score_heuristic_on_training(obj_fn, train_pairs)",
    "            if score >= 1.0:",
    "                result = _apply_fn_safe(obj_fn, test_input)",
    "                if result is not None:",
    "                    all_candidates.append((result, score, 'object_centric'))",
    "                    stats['object_solve'] = True",
    "                    stats['strategy'] = 'object_centric'",
    "",
    "    # =========================================================================",
    "    # TIER 3: Similarity-Based Transfer",
    "    # =========================================================================",
    "    if stats['heuristic_best_score'] < 1.0 and sim_index is not None:",
    "        transfer_heuristics = sim_index.get_transfer_heuristics(task, top_k=5)",
    "        for hname, hfn, sim_score in transfer_heuristics:",
    "            result = _apply_fn_safe(hfn, test_input)",
    "            if result is not None:",
    "                all_candidates.append((result, sim_score, f'similarity:{hname}'))",
    "                stats['similarity_transfer'] = True",
    "",
    "    # =========================================================================",
    "    # TIER 4: LLM Self-Consistency",
    "    # =========================================================================",
    "    llm_codes = []",
    "    if engine.is_available() and stats['heuristic_best_score'] < 1.0:",
    "        budget = MAX_LLM_TIME_SECONDS",
    "        llm_codes = llm_self_consistency_solve(task, engine, test_input_idx, max_time=budget)",
    "        stats['llm_candidates'] = len(llm_codes)",
    "        for code, score, passed in llm_codes:",
    "            result = safe_execute_code(code, test_input)",
    "            if result is not None:",
    "                all_candidates.append((result, score, 'llm'))",
    "            if score >= 0.8:",
    "                abstraction_lib.extract_from_verified_code(code)",
    "",
    "    # =========================================================================",
    "    # TIER 5: Evolutionary Synthesis",
    "    # =========================================================================",
    "    if llm_codes:",
    "        evolved = evolutionary_synthesis(llm_codes, train_pairs)",
    "        stats['evolved_candidates'] = len(evolved)",
    "        for code, score, passed in evolved:",
    "            result = safe_execute_code(code, test_input)",
    "            if result is not None:",
    "                all_candidates.append((result, score, 'evolved'))",
    "",
    "    # =========================================================================",
    "    # TIER 6: Test-Time LoRA Training (last resort)",
    "    # =========================================================================",
    "    if (engine.is_available() and stats['heuristic_best_score'] < 1.0",
    "            and not any(s >= 1.0 for _, s, _ in all_candidates)):",
    "        try:",
    "            lora_ok = engine.test_time_train(train_pairs, steps=LORA_STEPS)",
    "            if lora_ok:",
    "                # Generate one more candidate with LoRA-enhanced model",
    "                lora_codes = llm_self_consistency_solve(task, engine, test_input_idx,",
    "                                                       temperatures=[0.3], max_time=60)",
    "                for code, score, passed in lora_codes:",
    "                    result = safe_execute_code(code, test_input)",
    "                    if result is not None:",
    "                        all_candidates.append((result, score, 'lora'))",
    "                stats['lora_used'] = True",
    "        except Exception as e:",
    '            print(f"[LORA] Skip for task {task_id}: {e}")',
    "",
    "    # =========================================================================",
    "    # ENSEMBLE: Select Top-2 Distinct Candidates",
    "    # =========================================================================",
    "    all_candidates.sort(key=lambda x: -x[1])",
    "    selected = []",
    "    seen_hashes = set()",
    "    for grid, score, source in all_candidates:",
    "        h = grid_hash(grid)",
    "        if h not in seen_hashes:",
    "            seen_hashes.add(h)",
    "            selected.append(grid)",
    "            if len(selected) >= NUM_SUBMISSION_ATTEMPTS:",
    "                break",
    "",
    "    while len(selected) < NUM_SUBMISSION_ATTEMPTS:",
    "        if best_heuristics:",
    "            result = _apply_fn_safe(best_heuristics[0][1], test_input)",
    "            if result is not None:",
    "                h = grid_hash(result)",
    "                if h not in seen_hashes:",
    "                    seen_hashes.add(h)",
    "                    selected.append(result)",
    "                    continue",
    "        selected.append(_zero_grid_fallback(test_input))",
    "        break",
    "",
    "    stats['total_candidates'] = len(all_candidates)",
    "    if stats['heuristic_best_score'] >= 1.0:",
    "        stats['strategy'] = 'heuristic'",
    "    elif stats['object_solve']:",
    "        stats['strategy'] = 'object_centric'",
    "    elif any(s >= 1.0 for _, s, _ in all_candidates):",
    "        stats['strategy'] = 'llm_or_evolved'",
    "    elif all_candidates:",
    "        stats['strategy'] = 'partial_match'",
    "    else:",
    "        stats['strategy'] = 'zero_fallback'",
    "",
    "    return selected[:NUM_SUBMISSION_ATTEMPTS], stats",
    "",
    "",
    "def solve_all_tasks(",
    "    eval_tasks: Dict[str, Dict],",
    "    engine: LLMEngine,",
    "    sim_index: Optional['TaskSimilarityIndex'] = None,",
    "    max_tasks: Optional[int] = None,",
    "    total_time_budget: float = 12 * 3600 - 600,",
    ") -> Tuple[Dict[str, List], Dict[str, Any]]:",
    "    '''Solve all evaluation tasks with time budgeting.'''",
    "    submission: Dict[str, List] = {}",
    "    task_ids = list(eval_tasks.keys())",
    "    if max_tasks is not None:",
    "        task_ids = task_ids[:max_tasks]",
    "    total = len(task_ids)",
    "    per_task_budget = total_time_budget / max(total, 1)",
    "",
    '    print(f"\\n{"="*60}")',
'    print(f"SOLVING {total} evaluation tasks (v3 Tiered Ensemble)")',
'    print(f"Per-task budget: {per_task_budget:.0f}s | Total: {total_time_budget/3600:.1f}h")',
    '    print(f"{"="*60}\\n")',
    "",
    "    global_stats = {",
    "        'heuristic': 0, 'object': 0, 'similarity': 0,",
    "        'llm': 0, 'evolved': 0, 'partial_match': 0, 'zero_fallback': 0,",
    "        'total': total, 'solved': 0,",
    "    }",
    "",
    "    overall_start = time.time()",
    "    for idx, task_id in enumerate(tqdm(task_ids, desc='Solving tasks')):",
    "        task_start = time.time()",
    "        task = eval_tasks[task_id]",
    "",
    "        candidates, task_stats = solve_task(task, engine, 0, task_id, sim_index)",
    "",
    "        num_test = len(task['test'])",
    "        if num_test > 1:",
    "            all_attempts = []",
    "            for test_idx in range(num_test):",
    "                cands, _ = solve_task(task, engine, test_idx, task_id, sim_index)",
    "                all_attempts.extend(cands)",
    "            submission[task_id] = all_attempts[:NUM_SUBMISSION_ATTEMPTS * num_test]",
    "        else:",
    "            submission[task_id] = candidates",
    "",
    "        strategy = task_stats['strategy']",
    "        if strategy == 'heuristic':",
    "            global_stats['heuristic'] += 1",
    "            global_stats['solved'] += 1",
    "        elif strategy == 'object_centric':",
    "            global_stats['object'] += 1",
    "            global_stats['solved'] += 1",
    "        elif strategy in ('llm_or_evolved', 'evolved'):",
    "            global_stats['llm'] += 1",
    "            global_stats['solved'] += 1",
    "        elif strategy == 'partial_match':",
    "            global_stats['partial_match'] += 1",
    "        else:",
    "            global_stats['zero_fallback'] += 1",
    "",
    "        if (idx + 1) % 20 == 0 or idx == total - 1:",
    "            elapsed_total = time.time() - overall_start",
    "            rate = (idx + 1) / max(elapsed_total, 1)",
    "            remaining = (total - idx - 1) / max(rate, 0.001)",
    '            print(f"\\n  [{idx+1}/{total}] "\n',
    '                  f"Heuristic: {global_stats[\'heuristic\']} | "\n',
    '                  f"Object: {global_stats[\'object\']} | "\n',
    '                  f"LLM/Evolved: {global_stats[\'llm\']} | "\n',
    '                  f"Partial: {global_stats[\'partial_match\']} | "\n',
    '                  f"Zero: {global_stats[\'zero_fallback\']} | "\n',
    '                  f"Rate: {rate:.2f} tasks/s | ETA: {remaining/60:.0f}min")\n',
    "",
    "    total_elapsed = time.time() - overall_start",
    "    global_stats['elapsed_seconds'] = total_elapsed",
    "",
    '    print(f"\\n{"="*60}")',
    '    print(f"PIPELINE COMPLETE in {total_elapsed/60:.1f} minutes")',
    '    print(f\'  Heuristic:  {global_stats["heuristic"]}/{total}\')',
    '    print(f\'  Object:     {global_stats["object"]}/{total}\')',
    '    print(f\'  LLM/Evolved: {global_stats["llm"]}/{total}\')',
    '    print(f\'  Partial:    {global_stats["partial_match"]}/{total}\')',
    '    print(f\'  Zero:       {global_stats["zero_fallback"]}/{total}\')',
    '    print(f"  Abstractions: {abstraction_lib.get_stats()}")',
    '    print(f"{"="*60}\\n")',
    "",
    "    return submission, global_stats",
    "",
    "",
    "def save_submission(submission: Dict, path: str) -> None:",
    "    '''Write submission.json to disk.'''",
    "    os.makedirs(os.path.dirname(path), exist_ok=True)",
    '    with open(path, "w") as f:',
    "        json.dump(submission, f)",
    '    print(f"[SUBMISSION] Saved to {path}")',
'    print(f"[SUBMISSION] Tasks: {len(submission)}")',
'    print(f"[SUBMISSION] Total attempts: {sum(len(v) for v in submission.values())}")',
    "",
    "",
    'print("[ENSEMBLE] Tiered ensemble solver ready.")',
]
cells.append(code_cell(*solver_lines))

###############################################################################
# CELL 19: Execution (markdown)
###############################################################################
cells.append(md_cell(
    "## Execution\n",
    "\n",
    "Main entry point: load data, build similarity index, solve all tasks, save submission.",
))

###############################################################################
# CELL 20: Main execution
###############################################################################
main_lines = [
    "# ============================================================================",
    "# CELL 11: Main Entry Point",
    "# ============================================================================",
    "'''",
    "Main execution cell. Run all cells above, then this cell.",
    "Loads data, builds similarity index, solves evaluation tasks, saves submission.json.",
    "'''",
    "",
    "def main():",
    '    print("=" * 60)',
    '    print("ARC PRIZE 2026 - ARC-AGI-2 SOLVER v3")',
    '    print("Tiered Ensemble: Heuristics -> Objects -> Similarity -> LLM -> Evolve -> LoRA")',
    '    print("=" * 60)',
    '    print(f"Python: {sys.version}")',
    "    if _HAS_TORCH:",
    '        print(f"PyTorch: {torch.__version__}")',
    '        print(f"CUDA: {torch.cuda.is_available()}")',
    "        if torch.cuda.is_available():",
'            print(f"GPU: {torch.cuda.get_device_name(0)}")',
'    print(f"NumPy: {np.__version__}")',
    '    print(f"Heuristics: {len(ALL_HEURISTICS)}")',
    '    print(f"PEFT available: {_HAS_PEFT}")',
    "    print()",
    "",
    "    # --- Step 1: Load data ---",
    '    print("[STEP 1/5] Loading ARC data...")',
    "    eval_tasks, train_tasks = load_arc_data(DATA_DIR)",
    "",
    "    if not eval_tasks:",
    '        print("[ERROR] No evaluation tasks found!")',
'        print(f"  DATA_DIR: {DATA_DIR}")',
    "        if os.path.exists(DATA_DIR):",
'            print(f"  Contents: {os.listdir(DATA_DIR)}")',
    "        return",
    "",
    '    print(f"\\n  Sample tasks:")',
    "    for tid in list(eval_tasks.keys())[:3]:",
    "        print_task_summary(eval_tasks[tid], tid)",
    "",
    "    # --- Step 2: Build similarity index ---",
    '    print("\\n[STEP 2/5] Building task similarity index...")',
    "    similarity_index.build_index(train_tasks)",
    "",
    "    # --- Step 3: Load LLM ---",
    '    print("\\n[STEP 3/5] Loading LLM model...")',
    "    if llm.is_available():",
    "        llm.load()",
    "    else:",
    '        print("  [SKIP] LLM not available. Using heuristics + object reasoning only.")',
    "",
    "    # --- Step 4: Solve evaluation tasks ---",
    '    print("\\n[STEP 4/5] Solving evaluation tasks...")',
    "    submission, global_stats = solve_all_tasks(eval_tasks, llm, similarity_index)",
    "",
    "    # --- Step 5: Save submission ---",
    '    print("\\n[STEP 5/5] Saving submission...")',
    "    save_submission(submission, OUTPUT_PATH)",
    "",
    "    # --- Final summary ---",
    '    print("\\n" + "=" * 60)',
    '    print("FINAL SUMMARY")',
    '    print("=" * 60)',
    '    print(f"  Total tasks: {global_stats[\'total\']}")',
    '    print(f"  Heuristic solved: {global_stats[\'heuristic\']}")',
    '    print(f"  Object solved: {global_stats[\'object\']}")',
    '    print(f"  LLM/Evolved solved: {global_stats[\'llm\']}")',
    '    print(f"  Partial match: {global_stats[\'partial_match\']}")',
    '    print(f"  Zero fallback: {global_stats[\'zero_fallback\']}")',
    '    print(f"  Total time: {global_stats.get(\'elapsed_seconds\', 0)/60:.1f} min")',
    '    print(f"  Abstractions: {abstraction_lib.get_stats()}")',
    '    print(f"  Output: {OUTPUT_PATH}")',
    '    print("=" * 60)',
    "",
    "",
    'if __name__ == "__main__":',
    "    main()",
]
cells.append(code_cell(*main_lines))

###############################################################################
# Build the final notebook
###############################################################################
notebook = {
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.10.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5,
    "cells": cells,
}

output_path = "/home/z/my-project/download/arc_agi2_solver_v3.ipynb"
with open(output_path, "w") as f:
    json.dump(notebook, f, indent=1)

print(f"Notebook written to {output_path}")
print(f"Total cells: {len(cells)}")
print(f"Total size: {len(json.dumps(notebook))} bytes")
