#!/usr/bin/env python3
"""Generate ARC-AGI-2 Solver v3 notebook - Part 3 (cells 13-16)."""

import json

def L(*lines):
    result = []
    for i, line in enumerate(lines):
        if i < len(lines) - 1:
            result.append(line + "\n")
        else:
            result.append(line)
    return result

def md_cell(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": L(*lines)}

def code_cell(*lines):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": L(*lines)}

with open("/tmp/v3_cells_part2.json") as f:
    cells = json.load(f)

###############################################################################
# CELL 13: Heuristic Registration & Scoring
###############################################################################
reg_lines = [
    "# ============================================================================",
    "# CELL 7: Heuristic Registration, Parameterized Solvers & Scoring",
    "# ============================================================================",
    "",
    "# --- Register all base solvers -------------------------------------------",
    "BASE_HEURISTICS: List[Tuple[str, Callable]] = [",
    "    # Geometric",
    '    ("identity",          h_identity),',
    '    ("rotate90",          h_rotate90),',
    '    ("rotate180",         h_rotate180),',
    '    ("rotate270",         h_rotate270),',
    '    ("flip_h",            h_flip_h),',
    '    ("flip_v",            h_flip_v),',
    '    ("flip_diag",         h_flip_diag),',
    '    ("flip_anti_diag",    h_flip_anti_diag),',
    "    # Color",
    '    ("color_complement",  h_color_complement),',
    '    ("invert_colors",     h_invert_colors),',
    '    ("fill_most_common",  h_fill_most_common),',
    '    ("remap_colors",      h_remap_colors),',
    '    ("count_colors_out",  h_count_colors_output),',
    "    # Object",
    '    ("crop",              h_crop),',
    '    ("crop_each_color",   h_crop_each_color),',
    '    ("largest_comp",      h_extract_largest_component),',
    '    ("smallest_comp",     h_extract_smallest_component),',
    "    # Scaling",
    '    ("scale_2x",          h_scale_2x),',
    '    ("scale_3x",          h_scale_3x),',
    '    ("shrink_half",       h_shrink_by_half),',
    '    ("shrink_third",      h_shrink_by_third),',
    "    # Tiling",
    '    ("tile_2x2",          h_tile_2x2),',
    '    ("tile_3x3",          h_tile_3x3),',
    '    ("repeat_h",          h_repeat_h),',
    '    ("repeat_v",          h_repeat_v),',
    "    # Pattern",
    '    ("mirror_h_full",     h_mirror_h_full),',
    '    ("mirror_v_full",     h_mirror_v_full),',
    '    ("mirror_4way",       h_mirror_4way),',
    '    ("extract_border",    h_extract_border),',
    "    # Logic",
    '    ("threshold_binary",  h_threshold_binary),',
    '    ("replace_zero_dom",  h_replace_zero_with_dominant),',
    "]",
    "",
    "",
    "# --- Parameterized solvers ----------------------------------------------",
    "def _make_extract_color_fn(color):",
    "    def fn(grid):",
    "        return h_extract_color(grid, color)",
    "    return fn",
    "",
    "def _make_color_add_fn(k):",
    "    def fn(grid):",
    "        return h_color_add_k(grid, k)",
    "    return fn",
    "",
    "def _make_color_sub_fn(k):",
    "    def fn(grid):",
    "        return h_color_sub_k(grid, k)",
    "    return fn",
    "",
    "def _make_swap_fn(c1, c2):",
    "    def fn(grid):",
    "        return h_swap_colors(grid, c1, c2)",
    "    return fn",
    "",
    "def _make_replace_fn(old, new):",
    "    def fn(grid):",
    "        return h_replace_color(grid, old, new)",
    "    return fn",
    "",
    "for c in range(1, 10):",
    '    BASE_HEURISTICS.append((f"extract_color_{c}", _make_extract_color_fn(c)))',
    "for k in range(1, 10):",
    '    BASE_HEURISTICS.append((f"color_add_{k}", _make_color_add_fn(k)))',
    '    BASE_HEURISTICS.append((f"color_sub_{k}", _make_color_sub_fn(k)))',
    "# v3: parameterized swap and replace",
    "for c1 in range(1, 10):",
    "    for c2 in range(c1+1, 10):",
    '        BASE_HEURISTICS.append((f"swap_{c1}_{c2}", _make_swap_fn(c1, c2)))',
    "for old_c in range(1, 10):",
    "    for new_c in range(10):",
    "        if old_c != new_c:",
    '            BASE_HEURISTICS.append((f"replace_{old_c}_{new_c}", _make_replace_fn(old_c, new_c)))',
    "",
    "# --- v3 NEW base heuristics ---",
    "V3_NEW_HEURISTICS: List[Tuple[str, Callable]] = [",
]

# Add the v3 new heuristic entries
v3_entries = [
    ("dilate",                "h_dilate"),
    ("erode",                 "h_erode"),
    ("outline_objects",       "h_outline_objects"),
    ("fill_enclosed",         "h_fill_enclosed"),
    ("sort_rows_by_sum",      "h_sort_rows_by_sum"),
    ("sort_cols_by_sum",      "h_sort_cols_by_sum"),
    ("sort_rows_by_unique",   "h_sort_rows_by_unique"),
    ("sort_cols_by_unique",   "h_sort_cols_by_unique"),
    ("compress_rows",         "h_compress_rows"),
    ("compress_cols",         "h_compress_cols"),
    ("extract_nz_rows",       "h_extract_nonzero_rows"),
    ("extract_nz_cols",       "h_extract_nonzero_cols"),
    ("remove_dup_rows",       "h_remove_duplicate_rows"),
    ("remove_dup_cols",       "h_remove_duplicate_cols"),
    ("stack_vert",            "h_stack_objects_vertically"),
    ("stack_horiz",           "h_stack_objects_horizontally"),
    ("interleave_rows",       "h_interleave_rows"),
    ("interleave_cols",       "h_interleave_cols"),
    ("grow_objects",          "h_grow_objects"),
    ("shrink_objects",        "h_shrink_objects"),
    ("center_objects",        "h_center_objects"),
    ("extract_diagonal",      "h_extract_diagonal"),
    ("extract_anti_diagonal", "h_extract_anti_diagonal"),
    ("rolling_h",             "h_rolling_pattern_h"),
    ("rolling_v",             "h_rolling_pattern_v"),
    ("detect_tile",           "h_detect_and_extract_tile"),
    ("distribute_evenly",     "h_distribute_evenly"),
]
for name, fn_name in v3_entries:
    reg_lines.append(f'    ("{name}",                {fn_name}),')

# Add specific swap/replace entries
swap_entries = [
    ("swap_colors_1_2", "_make_swap_fn(1, 2)"),
    ("swap_colors_2_3", "_make_swap_fn(2, 3)"),
    ("swap_colors_1_3", "_make_swap_fn(1, 3)"),
    ("swap_colors_1_4", "_make_swap_fn(1, 4)"),
    ("swap_colors_2_4", "_make_swap_fn(2, 4)"),
    ("replace_1_2", "_make_replace_fn(1, 2)"),
    ("replace_2_1", "_make_replace_fn(2, 1)"),
    ("replace_1_0", "_make_replace_fn(1, 0)"),
    ("replace_2_0", "_make_replace_fn(2, 0)"),
    ("replace_3_0", "_make_replace_fn(3, 0)"),
    ("replace_4_0", "_make_replace_fn(4, 0)"),
    ("replace_5_0", "_make_replace_fn(5, 0)"),
    ("replace_0_1", "_make_replace_fn(0, 1)"),
    ("replace_0_2", "_make_replace_fn(0, 2)"),
    ("replace_0_3", "_make_replace_fn(0, 3)"),
]
for name, fn_expr in swap_entries:
    reg_lines.append(f'    ("{name}",           {fn_expr}),')

reg_lines.extend([
    "]",
    "",
    "",
    "# --- Composite solvers (2-3 operation chains) ---------------------------",
    "COMPOSITE_HEURISTICS: List[Tuple[str, Callable]] = []",
    "",
    "def make_composite(funcs):",
    "    def fn(grid):",
    "        result = copy.deepcopy(grid)",
    "        for f in funcs:",
    "            try:",
    "                result = normalize_grid(f(result))",
    "                if result is None:",
    "                    return None",
    "            except Exception:",
    "                return None",
    "        return result",
    "    return fn",
    "",
    "# v2 composites",
    "COMPOSITE_DEFS = [",
])

# v2 composite defs
v2_composites = [
    ("crop_rotate90",        "h_crop, h_rotate90"),
    ("crop_rotate180",       "h_crop, h_rotate180"),
    ("crop_flip_h",          "h_crop, h_flip_h"),
    ("crop_flip_v",          "h_crop, h_flip_v"),
    ("crop_scale2x",         "h_crop, h_scale_2x"),
    ("largest_comp_crop",    "h_extract_largest_component, h_crop"),
    ("crop_mirror_h",        "h_crop, h_mirror_h_full"),
    ("crop_mirror_v",        "h_crop, h_mirror_v_full"),
    ("rotate90_crop",        "h_rotate90, h_crop"),
    ("flip_h_crop",          "h_flip_h, h_crop"),
    ("flip_v_crop",          "h_flip_v, h_crop"),
    ("threshold_crop",       "h_threshold_binary, h_crop"),
    ("remap_crop",           "h_remap_colors, h_crop"),
    ("crop_extract_color_1", "h_crop, _make_extract_color_fn(1)"),
    ("crop_extract_color_2", "h_crop, _make_extract_color_fn(2)"),
    ("crop_extract_color_3", "h_crop, _make_extract_color_fn(3)"),
]
for name, fns_str in v2_composites:
    reg_lines.append(f'    ("{name}",        [{fns_str}]),')

reg_lines.append("]")

# v3 composite defs
v3_composites = [
    ("crop_dilate_outline",      "h_crop, h_dilate, h_outline_objects"),
    ("threshold_erode_crop",     "h_threshold_binary, h_erode, h_crop"),
    ("crop_fill_enclosed_crop",  "h_crop, h_fill_enclosed, h_crop"),
    ("crop_dilate_crop",         "h_crop, h_dilate, h_crop"),
    ("crop_erode_crop",          "h_crop, h_erode, h_crop"),
    ("crop_outline_crop",        "h_crop, h_outline_objects, h_crop"),
    ("threshold_crop_dilate",    "h_threshold_binary, h_crop, h_dilate"),
    ("crop_sort_rows_sum",       "h_crop, h_sort_rows_by_sum"),
    ("crop_sort_cols_sum",       "h_crop, h_sort_cols_by_sum"),
    ("crop_compress_rows_cols",  "h_crop, h_compress_rows, h_compress_cols"),
    ("compress_crop",            "h_compress_rows, h_compress_cols, h_crop"),
    ("crop_detect_tile",         "h_crop, h_detect_and_extract_tile"),
    ("tile_crop",                "h_detect_and_extract_tile, h_crop"),
    ("crop_largest_outline",     "h_crop, h_extract_largest_component, h_outline_objects"),
    ("remap_threshold_crop",     "h_remap_colors, h_threshold_binary, h_crop"),
    ("crop_mirror_h_crop",       "h_crop, h_mirror_h_full, h_crop"),
    ("crop_mirror_v_crop",       "h_crop, h_mirror_v_full, h_crop"),
    ("crop_interleave_rows",     "h_crop, h_interleave_rows"),
    ("crop_interleave_cols",     "h_crop, h_interleave_cols"),
    ("crop_stack_vert",          "h_crop, h_stack_objects_vertically"),
    ("crop_stack_horiz",         "h_crop, h_stack_objects_horizontally"),
    ("crop_center",              "h_crop, h_center_objects"),
    ("crop_rolling_h",           "h_crop, h_rolling_pattern_h"),
    ("crop_rolling_v",           "h_crop, h_rolling_pattern_v"),
    ("crop_replace_1_2",         "h_crop, _make_replace_fn(1, 2)"),
    ("crop_replace_2_1",         "h_crop, _make_replace_fn(2, 1)"),
    ("crop_swap_1_2",            "h_crop, _make_swap_fn(1, 2)"),
    ("crop_swap_2_3",            "h_crop, _make_swap_fn(2, 3)"),
    ("extract_color_1_crop",     "_make_extract_color_fn(1), h_crop"),
    ("extract_color_2_crop",     "_make_extract_color_fn(2), h_crop"),
    ("extract_color_3_crop",     "_make_extract_color_fn(3), h_crop"),
]

reg_lines.append("")
reg_lines.append("V3_COMPOSITE_DEFS = [")
for name, fns_str in v3_composites:
    reg_lines.append(f'    ("{name}",         [{fns_str}]),')
reg_lines.append("]")

reg_lines.extend([
    "",
    "for name, fns in COMPOSITE_DEFS + V3_COMPOSITE_DEFS:",
    "    COMPOSITE_HEURISTICS.append((name, make_composite(fns)))",
    "",
    "ALL_HEURISTICS = BASE_HEURISTICS + V3_NEW_HEURISTICS + COMPOSITE_HEURISTICS",
    "",
    "",
    "# === SCORING =============================================================",
    "",
    "def score_heuristic_on_training(",
    "    heuristic_fn: Callable,",
    "    train_pairs: List[Dict],",
    ") -> Tuple[float, int, int]:",
    "    '''Score a heuristic against training pairs. Returns (score, num_passed, total).'''",
    "    passed = 0",
    "    total = len(train_pairs)",
    "    for pair in train_pairs:",
    "        try:",
    '            result = heuristic_fn(pair["input"])',
    "            norm = normalize_grid(result)",
    '            if norm is not None and grids_equal(norm, pair["output"]):',
    "                passed += 1",
    "        except Exception:",
    "            continue",
    "    return (passed / total if total > 0 else 0.0, passed, total)",
    "",
    "",
    "def find_best_heuristics(",
    "    train_pairs: List[Dict],",
    "    min_score: float = 1.0,",
    "    max_results: int = 5,",
    ") -> List[Tuple[str, Callable, float, int, int]]:",
    "    '''Find heuristics scoring >= min_score. Returns (name, fn, score, passed, total).'''",
    "    results = []",
    "    for name, fn in ALL_HEURISTICS:",
    "        score, passed, total = score_heuristic_on_training(fn, train_pairs)",
    "        if score >= min_score:",
    "            results.append((name, fn, score, passed, total))",
    "    results.sort(key=lambda x: (-x[2], -x[3], x[0]))",
    "    return results[:max_results]",
    "",
    "",
    "def find_best_partial_heuristics(",
    "    train_pairs: List[Dict],",
    "    max_results: int = 10,",
    ") -> List[Tuple[str, Callable, float, int, int]]:",
    "    '''Find heuristics sorted by partial-match score.'''",
    "    results = []",
    "    for name, fn in ALL_HEURISTICS:",
    "        score, passed, total = score_heuristic_on_training(fn, train_pairs)",
    "        if score > 0.0:",
    "            results.append((name, fn, score, passed, total))",
    "    results.sort(key=lambda x: (-x[2], -x[3], x[0]))",
    "    return results[:max_results]",
    "",
    "",
    'print(f\'[HEURISTICS] Total registered: {len(ALL_HEURISTICS)} \'',
    '      f\'({len(BASE_HEURISTICS)} base + {len(V3_NEW_HEURISTICS)} v3-new + {len(COMPOSITE_HEURISTICS)} composite)\')',
])

cells.append(code_cell(*reg_lines))

###############################################################################
# CELL 14: Safe Code Execution
###############################################################################
exec_lines = [
    "# ============================================================================",
    "# CELL 8: Safe Code Execution & Verification",
    "# ============================================================================",
    "'''Sandboxed code execution with timeout and partial-match scoring.'''",
    "",
    "def _run_code_in_thread(code, input_grid, result_container, error_container):",
    "    '''Worker thread for code execution.'''",
    "    try:",
    "        local_ns = {'np': np, 'copy': copy, 'math': math,",
    "                     'Counter': Counter, 'defaultdict': defaultdict,",
    "                     'set': set, 'sorted': sorted, 'len': len, 'range': range,",
    "                     'enumerate': enumerate, 'zip': zip, 'list': list,",
    "                     'int': int, 'float': float, 'bool': bool, 'max': max, 'min': min,",
    "                     'abs': abs, 'sum': sum, 'any': any, 'all': all,",
    "                     'deque': deque,",
    "                     'print': lambda *a, **k: None,",
    "                     '__builtins__': __builtins__}",
    "        exec(code, local_ns)",
    "        transform_fn = local_ns.get('transform')",
    "        if transform_fn is None:",
    '            error_container.append("No transform function defined.")',
    "            return",
    "        result = transform_fn(copy.deepcopy(input_grid))",
    "        result_container.append(result)",
    "    except Exception as e:",
    "        error_container.append(str(e))",
    "",
    "",
    "def safe_execute_code(",
    "    code: str,",
    "    input_grid: List[List[int]],",
    "    timeout: float = CODE_TIMEOUT_SECONDS,",
    ") -> Optional[List[List[int]]]:",
    "    '''Execute code safely with timeout. Returns output grid or None.'''",
    "    result_container = []",
    "    error_container = []",
    "    thread = threading.Thread(",
    "        target=_run_code_in_thread,",
    "        args=(code, input_grid, result_container, error_container),",
    "        daemon=True,",
    "    )",
    "    thread.start()",
    "    thread.join(timeout=timeout)",
    "    if thread.is_alive() or error_container or not result_container:",
    "        return None",
    "    return normalize_grid(result_container[0])",
    "",
    "",
    "def verify_code_on_training(",
    "    code: str,",
    "    train_pairs: List[Dict],",
    ") -> Tuple[float, int, int]:",
    "    '''Verify code against training pairs. Returns (score, num_passed, total).'''",
    "    passed = 0",
    "    total = len(train_pairs)",
    "    for pair in train_pairs:",
    "        result = safe_execute_code(code, pair['input'])",
    '        if result is not None and grids_equal(result, pair["output"]):',
    "            passed += 1",
    "    return (passed / total if total > 0 else 0.0, passed, total)",
    "",
    "",
    "def extract_function_code(llm_output: str) -> Optional[str]:",
    "    '''Extract transform() function from raw LLM text output.'''",
    "    if not llm_output:",
    "        return None",
    '    fence_match = re.search(r"```(?:python)?\\s*\\n?(.*?)```", llm_output, re.DOTALL)',
    "    if fence_match:",
    "        code_block = fence_match.group(1).strip()",
    '        if "def transform" in code_block:',
    "            fn_match = re.search(",
    '                r"(def\\s+transform\\s*\\(\\s*input_grid\\s*\\)\\s*:.*?)"',
    '                r"(?=\\n(?:def |class |$))",',
    "                code_block, re.DOTALL",
    "            )",
    "            if fn_match:",
    "                return fn_match.group(1).strip()",
    "            return code_block",
    "    fn_match = re.search(",
    '        r"(def\\s+transform\\s*\\(\\s*input_grid\\s*\\)\\s*:.*?)"',
    '        r"(?=\\n(?:def |class |$))",',
    "        llm_output, re.DOTALL",
    "    )",
    "    if fn_match:",
    "        return fn_match.group(1).strip()",
    '    idx = llm_output.find("def transform")',
    "    if idx >= 0:",
    "        return llm_output[idx:].strip()",
    "    return None",
    "",
    "",
    'print("[EXEC] Safe code execution and verification ready.")',
]
cells.append(code_cell(*exec_lines))

###############################################################################
# CELL 15: LLM Loading + Test-Time Training (markdown)
###############################################################################
cells.append(md_cell(
    "## LLM Loading, Self-Consistency & Test-Time Training\n",
    "\n",
    "- **Lazy-loaded** Qwen3-4B with 4-bit quantization\n",
    "- **Self-consistency**: 3 candidates at T=0.2, 0.4, 0.6, verified against all training pairs\n",
    "- **Test-time LoRA**: Last-resort PEFT fine-tuning (rank=8, 50 steps, lr=5e-5)\n",
    "- **Evolutionary synthesis**: 15 population, 4 generations, new mutate_swap_lines operator\n",
))

###############################################################################
# CELL 16: LLM Engine + Evolution + Abstraction (code)
###############################################################################
# Write this cell to a separate file to avoid quoting issues
llm_lines = [
    "# ============================================================================",
    "# CELL 9: LLM Engine, DreamCoder Abstraction, Self-Consistency & Evolution",
    "# ============================================================================",
    "",
    "# === DREAMCODER ABSTRACTION LIBRARY =======================================",
    "",
    "class AbstractionLibrary:",
    "    '''Manages a library of reusable code abstractions.'''",
    "",
    "    def __init__(self):",
    "        self.abstractions: Dict[str, Dict] = {}",
    "        self._init_builtin_abstractions()",
    "",
    "    def _init_builtin_abstractions(self):",
    "        builtins = {",
    '            "find_bounding_box": (',
    '                "def find_bounding_box(grid):\\n"',
    '                "    rows = [i for i, row in enumerate(grid) if any(c != 0 for c in row)]\\n"',
    '                "    cols = [j for j in range(len(grid[0])) if any(grid[i][j] != 0 for i in range(len(grid)))]\\n"',
    '                "    if not rows or not cols: return (0, 0, 0, 0)\\n"',
    '                "    return (min(rows), min(cols), max(rows), max(cols))\\n",',
    '                ["geometry", "crop"]',
    "            ),",
    '            "crop_grid": (',
    '                "def crop_grid(grid):\\n"',
    '                "    import numpy as np\\n"',
    '                "    g = np.array(grid)\\n"',
    '                "    r = np.where(g.any(axis=1))[0]\\n"',
    '                "    c = np.where(g.any(axis=0))[0]\\n"',
    '                "    if len(r) == 0: return [[0]]\\n"',
    '                "    return g[r[0]:r[-1]+1, c[0]:c[-1]+1].tolist()\\n",',
    '                ["crop", "geometry"]',
    "            ),",
    '            "find_objects": (',
    '                "def find_objects(grid, connectivity=4):\\n"',
    '                "    import numpy as np\\n"',
    '                "    g = np.array(grid)\\n"',
    '                "    visited = np.zeros_like(g, dtype=bool)\\n"',
    '                "    objects = []\\n"',
    '                "    neighbors = [(-1,0),(1,0),(0,-1),(0,1)] if connectivity==4 else [(-1,0),(1,0),(0,-1),(0,1),(-1,-1),(-1,1),(1,-1),(1,1)]\\n"',
    '                "    for i in range(g.shape[0]):\\n"',
    '                "        for j in range(g.shape[1]):\\n"',
    '                "            if g[i,j] != 0 and not visited[i,j]:\\n"',
    '                "                color = int(g[i,j])\\n"',
    '                "                obj = []\\n"',
    '                "                stack = [(i,j)]\\n"',
    '                "                while stack:\\n"',
    '                "                    ci,cj = stack.pop()\\n"',
    '                "                    if ci<0 or ci>=g.shape[0] or cj<0 or cj>=g.shape[1] or visited[ci,cj] or g[ci,cj]!=color: continue\\n"',
    '                "                    visited[ci,cj] = True\\n"',
    '                "                    obj.append((ci,cj))\\n"',
    '                "                    for di,dj in neighbors: stack.append((ci+di,cj+dj))\\n"',
    '                "                objects.append(obj)\\n"',
    '                "    return objects\\n",',
    '                ["objects", "perception"]',
    "            ),",
    '            "get_color_counts": (',
    '                "def get_color_counts(grid):\\n"',
    '                "    counts = {}\\n"',
    '                "    for row in grid:\\n"',
    '                "        for v in row:\\n"',
    '                "            counts[v] = counts.get(v, 0) + 1\\n"',
    '                "    return counts\\n",',
    '                ["color", "counting"]',
    "            ),",
    "        }",
    "        for name, (code, cats) in builtins.items():",
    "            self.abstractions[name] = {'code': code, 'uses': 0, 'categories': cats}",
    "",
    "    def add_abstraction(self, name: str, code: str, categories: List[str] = None):",
    "        if name in self.abstractions:",
    "            return",
    '        if not re.search(r"^def\\s+\\w+", code, re.MULTILINE):',
    "            return",
    "        self.abstractions[name] = {'code': code, 'uses': 1, 'categories': categories or []}",
    "",
    "    def extract_from_verified_code(self, code: str) -> int:",
    "        new_count = 0",
    '        pattern = re.compile(r"(def\\s+(\\w+)\\s*\\([^)]*\\)\\s*:(?:.*?)(?=\\ndef\\s|\\Z))", re.DOTALL)',
    "        for match in pattern.finditer(code):",
    "            fn_code = match.group(1)",
    "            fn_name = match.group(2)",
    '            if fn_name == "transform":',
    "                continue",
    "            if 20 < len(fn_code) < 1000:",
    "                self.add_abstraction(fn_name, fn_code)",
    "                new_count += 1",
    "        return new_count",
    "",
    "    def get_relevant_abstractions(self, categories: List[str] = None, max_n: int = 5) -> str:",
    "        candidates = []",
    "        for name, info in self.abstractions.items():",
    "            if categories:",
    "                overlap = set(info['categories']) & set(categories)",
    "                score = len(overlap) * 10 + info['uses']",
    "            else:",
    "                score = info['uses']",
    "            candidates.append((name, info['code'], score))",
    "        candidates.sort(key=lambda x: -x[2])",
    "        selected = candidates[:max_n]",
    "        if not selected:",
    "            return ''",
    '        lines = ["# Available helper functions (you may use these):", ""]',
    "        for name, code, _ in selected:",
    '            lines.append(f"# {name}:")',
    "            lines.append(code)",
    "            lines.append('')",
    '        return "\\n".join(lines)',
    "",
    "    def get_stats(self) -> Dict[str, int]:",
    "        return {'total': len(self.abstractions),",
    '                "builtin": sum(1 for v in self.abstractions.values() if v["uses"] == 0),',
    '                "learned": sum(1 for v in self.abstractions.values() if v["uses"] > 0)}',
    "",
    "",
    "abstraction_lib = AbstractionLibrary()",
    'print(f\'[ABSTRACTIONS] Library initialized with {abstraction_lib.get_stats()["builtin"]} builtins.\')',
    "",
    "",
    "# === LLM ENGINE ===========================================================",
    "",
    "class LLMEngine:",
    "    '''Manages the LLM lifecycle. Lazy-loads the model on first use.'''",
    "",
    "    def __init__(self):",
    "        self.model = None",
    "        self.tokenizer = None",
    "        self._loaded = False",
    "        self._load_attempted = False",
    "        self._base_model = None",
    "",
    "    def is_available(self) -> bool:",
    "        if self._load_attempted:",
    "            return self.model is not None",
    "        if not _HAS_TORCH or not _HAS_TRANSFORMERS:",
    "            return False",
    "        try:",
    "            if not torch.cuda.is_available():",
    "                return False",
    "        except Exception:",
    "            return False",
    "        return True",
    "",
    "    def load(self):",
    "        if self._loaded:",
    "            return",
    "        self._load_attempted = True",
    '        print(f"[LLM] Loading {MODEL_NAME}...")',
    "        t0 = time.time()",
    "        try:",
    "            model_kwargs = {",
    "                'torch_dtype': torch.float16,",
    '                "device_map": "auto",',
    "                'trust_remote_code': True,",
    "            }",
    "            if QUANTIZATION_4BIT and _HAS_BNB:",
    "                bnb_config = BitsAndBytesConfig(",
    "                    load_in_4bit=True,",
    '                    bnb_4bit_quant_type="nf4",',
    "                    bnb_4bit_compute_dtype=torch.float16,",
    "                    bnb_4bit_use_double_quant=True,",
    "                )",
    '                model_kwargs["quantization_config"] = bnb_config',
    '                print("[LLM] Using 4-bit quantization.")',
    "            self.tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True)",
    "            if self.tokenizer.pad_token is None:",
    "                self.tokenizer.pad_token = self.tokenizer.eos_token",
    "            self.model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, **model_kwargs)",
    "            self.model.eval()",
    "            self._base_model = self.model",
    "            self._loaded = True",
    '            print(f"[LLM] Model loaded in {time.time()-t0:.1f}s")',
    "        except Exception as e:",
    '            print(f"[LLM] Failed to load: {e}")',
    "            self.model = None",
    "            self.tokenizer = None",
    "",
    "    def generate(self, messages, temperature=0.3, max_new_tokens=MAX_NEW_TOKENS):",
    "        if not self._loaded:",
    "            self.load()",
    "        if self.model is None or self.tokenizer is None:",
    "            return None",
    "        try:",
    "            text = self.tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)",
    "            inputs = self.tokenizer(text, return_tensors='pt', truncation=True, max_length=MAX_INPUT_TOKENS).to(self.model.device)",
    "            with torch.no_grad():",
    "                outputs = self.model.generate(",
    "                    **inputs,",
    "                    max_new_tokens=max_new_tokens,",
    "                    temperature=temperature,",
    "                    top_p=0.92,",
    "                    do_sample=(temperature > 0),",
    "                    pad_token_id=self.tokenizer.pad_token_id,",
    "                    eos_token_id=self.tokenizer.eos_token_id,",
    "                )",
    '            new_tokens = outputs[0][inputs["input_ids"].shape[1]:]',
    "            return self.tokenizer.decode(new_tokens, skip_special_tokens=True)",
    "        except Exception as e:",
    '            print(f"[LLM] Generation failed: {e}")',
    "            return None",
    "",
    "    def test_time_train(self, train_pairs, steps=LORA_STEPS, lr=LORA_LR):",
    "        '''v3 NEW: Test-time LoRA fine-tuning on training pairs.'''",
    "        if not _HAS_PEFT or not self._loaded:",
    "            return None",
    '        print(f"[LORA] Starting test-time training ({steps} steps, lr={lr})...")',
    "        try:",
    "            lora_config = LoraConfig(",
    "                task_type=TaskType.CAUSAL_LM,",
    "                r=LORA_RANK,",
    "                lora_alpha=LORA_ALPHA,",
    "                lora_dropout=0.05,",
    "                target_modules=LORA_TARGET_MODULES,",
    "            )",
    "            if self._base_model is not None:",
    "                model = get_peft_model(self._base_model, lora_config)",
    "                self.model = model",
    "            else:",
    "                return None",
    "            model.train()",
    "            texts = []",
    "            for pair in train_pairs:",
    '                inp_str = grid_to_str(pair["input"], "Input")',
    '                out_str = grid_to_str(pair["output"], "Output")',
    '                texts.append(f"Input:\\n{inp_str}\\nOutput:\\n{out_str}")',
    "            optimizer = torch.optim.AdamW(model.parameters(), lr=lr)",
    "            for step in range(steps):",
    "                for text in texts:",
    "                    inputs = self.tokenizer(text, return_tensors='pt', truncation=True, max_length=512)",
    "                    inputs = {k: v.to(model.device) for k, v in inputs.items()}",
    "                    outputs = model(**inputs, labels=inputs['input_ids'])",
    "                    loss = outputs.loss",
    "                    loss.backward()",
    "                    optimizer.step()",
    "                    optimizer.zero_grad()",
    "                if (step + 1) % 10 == 0:",
    '                    print(f"[LORA] Step {step+1}/{steps}, loss={loss.item():.4f}")',
    "            model.eval()",
    '            print("[LORA] Test-time training complete.")',
    "            return True",
    "        except Exception as e:",
    '            print(f"[LORA] Test-time training failed: {e}")',
    "            return None",
    "",
    "",
    "llm = LLMEngine()",
    'print(f"[LLM] Engine initialized. Available: {llm.is_available()}")',
    "",
    "",
    "# === LLM PROMPTS & SELF-CONSISTENCY ======================================",
    "",
    'PHASE1_SYSTEM = \'\'\'You are an expert at analyzing visual pattern puzzles (ARC tasks).',
    "You will see input-output grid pairs. Your job is to:",
    "1. Describe the transformation rule in clear, precise natural language.",
    "2. Identify key features: colors, shapes, objects, spatial relationships.",
    "3. Note any conditional logic (different rules for different inputs).",
    "4. Be specific about dimensions, positions, and color values.",
    "",
    "Color reference: 0=black, 1=blue, 2=red, 3=green, 4=yellow,",
    "5=gray, 6=magenta, 7=orange, 8=cyan, 9=brown.",
    "",
    "Think step by step. Be thorough and precise.\'\'\'",
    "",
    "",
    'PHASE2_SYSTEM = \'\'\'You are an expert Python programmer who solves ARC puzzles.',
    "You will be given:",
    "1. A natural language analysis of the transformation rule.",
    "2. The input-output grid examples.",
    "3. Helper functions you may use.",
    "",
    "Write a single Python function `transform(input_grid)` that implements the rule.",
    "",
    "Rules:",
    "- input_grid is a list of lists of ints (each 0-9).",
    "- Return a list of lists of ints.",
    "- Do NOT print anything.",
    "- Only output the function code. No explanation.",
    "- Use numpy as np if helpful.",
    "- Handle variable-sized inputs correctly.",
    "- You may use the provided helper functions.\'\'\'",
    "",
    "",
    "def build_enhanced_task_prompt(task: Dict, test_input_idx: int = 0) -> str:",
    "    parts = []",
    '    for i, pair in enumerate(task["train"]):',
    '        inp_desc = describe_grid_natural_language(pair["input"], f"Example {i+1} Input")',
    '        out_desc = describe_grid_natural_language(pair["output"], f"Example {i+1} Output")',
    "        parts.append(inp_desc)",
    '        parts.append(grid_to_str(pair["input"]))',
    "        parts.append(out_desc)",
    '        parts.append(grid_to_str(pair["output"]))',
    '        inp_s = grid_shape(pair["input"])',
    '        out_s = grid_shape(pair["output"])',
    "        if inp_s != out_s:",
    '            parts.append(f"Size change: {inp_s[0]}x{inp_s[1]} -> {out_s[0]}x{out_s[1]}")',
    "        parts.append('')",
    '    test_input = task["test"][test_input_idx]["input"]',
    '    parts.append(describe_grid_natural_language(test_input, "Test Input"))',
    '    parts.append(grid_to_str(test_input))',
    '    return "\\n".join(parts)',
    "",
    "",
    "def llm_self_consistency_solve(",
    "    task: Dict,",
    "    engine: LLMEngine,",
    "    test_input_idx: int = 0,",
    "    temperatures: List[float] = [0.2, 0.4, 0.6],",
    "    max_time: float = MAX_LLM_TIME_SECONDS,",
    ") -> List[Tuple[str, float, int]]:",
    "    '''v3 Self-consistency: 3 candidates at different temperatures.'''",
    "    if not engine.is_available():",
    "        return []",
    "    train_pairs = task['train']",
    "    task_prompt = build_enhanced_task_prompt(task, test_input_idx)",
    "    results = []",
    "    t_start = time.time()",
    "    for temp in temperatures:",
    "        if time.time() - t_start > max_time:",
    "            break",
    "        analysis_messages = [",
    '            {"role": "system", "content": PHASE1_SYSTEM},',
    '            {"role": "user", "content": f"Analyze this ARC task:\\n\\n{task_prompt}\\n\\nDescribe the transformation rule precisely."},',
    "        ]",
    "        analysis = engine.generate(analysis_messages, temperature=temp, max_new_tokens=1024)",
    "        if not analysis:",
    "            continue",
    "        helper_code = abstraction_lib.get_relevant_abstractions(max_n=3)",
    "        code_messages = [",
    '            {"role": "system", "content": PHASE2_SYSTEM},',
    '            {"role": "user", "content":',
    '             f"## Pattern Analysis\\n{analysis}\\n\\n"',
    '             f"## Examples\\n{task_prompt}\\n\\n"',
    '             f"{helper_code}\\n"',
    '             "Write a transform(input_grid) function."},',
    "        ]",
    "        raw_code = engine.generate(code_messages, temperature=temp, max_new_tokens=MAX_NEW_TOKENS)",
    "        if not raw_code:",
    "            continue",
    "        code = extract_function_code(raw_code)",
    "        if not code:",
    "            continue",
    "        score, passed, total = verify_code_on_training(code, train_pairs)",
    "        if score > 0.0:",
    "            results.append((code, score, passed))",
    "    seen = {}",
    "    for code, score, passed in results:",
    '        h = hashlib.md5(code.encode()).hexdigest()[:12]',
    "        if h not in seen or score > seen[h][1]:",
    "            seen[h] = (code, score, passed)",
    "    return [(c, s, p) for c, s, p in seen.values()]",
    "",
    "",
    "# === EVOLUTIONARY PROGRAM SYNTHESIS =======================================",
    "",
    "class ProgramMutator:",
    "    '''Mutates and cross-breeds Python code to generate new candidates.'''",
    "",
    "    NUMERIC_MUTATIONS = {",
    '        "0": ["1", "0", "-1"],',
    '        "1": ["0", "2", "1", "-1"],',
    '        "2": ["1", "3", "2", "0"],',
    '        "3": ["2", "4", "3", "1"],',
    '        "4": ["3", "5", "4", "2"],',
    '        "5": ["4", "6", "5", "3"],',
    '        "6": ["5", "7", "6", "4"],',
    '        "7": ["6", "8", "7", "5"],',
    '        "8": ["7", "9", "8", "6"],',
    '        "9": ["8", "0", "9", "7"],',
    "    }",
    "",
    "    OP_SWAPS = [",
    '        ("[:, ::-1]", "[::-1, :]"),',
    '        ("[::-1, :]", "[:, ::-1]"),',
    '        ("rot90(g, 1)", "rot90(g, 3)"),',
    '        ("rot90(g, 3)", "rot90(g, 1)"),',
    '        ("rot90(g, 2)", "g"),',
    '        (".T", ""),',
    '        ("(g + 1)", "(g - 1)"),',
    '        ("(g - 1)", "(g + 1)"),',
    '        ("% 10", ""),',
    '        ("> 0", "== 0"),',
    '        ("== 0", "> 0"),',
    '        ("any(axis=1)", "any(axis=0)"),',
    '        ("any(axis=0)", "any(axis=1)"),',
    '        ("axis=0", "axis=1"),',
    '        ("axis=1", "axis=0"),',
    "    ]",
    "",
    "    def mutate_numeric(self, code):",
    "        mutations = []",
    "        for original, replacements in self.NUMERIC_MUTATIONS.items():",
    "            for replacement in replacements:",
    "                if replacement == original:",
    "                    continue",
    '                pattern = re.compile(r\'(?<![\\w])\' + re.escape(original) + r\'(?![\\w])\')',
    "                mutated = pattern.sub(replacement, code)",
    "                if mutated != code:",
    "                    mutations.append(mutated)",
    "        return mutations",
    "",
    "    def mutate_operations(self, code):",
    "        mutations = []",
    "        for old_op, new_op in self.OP_SWAPS:",
    "            if old_op in code:",
    "                mutations.append(code.replace(old_op, new_op, 1))",
    "        return mutations",
    "",
    "    def mutate_color_value(self, code):",
    "        mutations = []",
    "        for c in range(10):",
    "            for c2 in range(10):",
    "                if c == c2:",
    "                    continue",
    '                for pattern_str in [f"== {c}", f"!= {c}", f"({c})", f"[{c}]", f"= {c}"]:',
    "                    if pattern_str in code:",
    '                        mutated = code.replace(pattern_str, pattern_str.replace(str(c), str(c2)), 1)',
    "                        if mutated != code:",
    "                            mutations.append(mutated)",
    "            if len(mutations) >= 5:",
    "                break",
    "        return mutations[:5]",
    "",
    "    def mutate_indentation_logic(self, code):",
    "        mutations = []",
    '        if "if " in code:',
    '            mutations.append(code.replace(">", "<", 1))',
    '            mutations.append(code.replace("<", ">", 1))',
    '            mutations.append(code.replace(">=", "<=", 1))',
    '            mutations.append(code.replace("<=", ">=", 1))',
    "        return [m for m in mutations if m != code][:3]",
    "",
    "    def mutate_swap_lines(self, code):",
    "        '''v3 NEW: Swap two random non-empty code lines.'''",
    "        lines = code.split('\\n')",
    "        non_empty = [(i, l) for i, l in enumerate(lines) if l.strip() and not l.strip().startswith('#')]",
    "        if len(non_empty) < 2:",
    "            return []",
    "        mutations = []",
    "        random.seed(42)",
    "        for _ in range(3):",
    "            idx1, idx2 = random.sample(range(len(non_empty)), 2)",
    "            i1, l1 = non_empty[idx1]",
    "            i2, l2 = non_empty[idx2]",
    "            new_lines = lines.copy()",
    "            new_lines[i1], new_lines[i2] = l2, l1",
    "            mutations.append('\\n'.join(new_lines))",
    "        return mutations",
    "",
    "    def crossover(self, code1, code2):",
    "        children = []",
    "        def extract_helpers(code):",
    "            helpers = []",
    '            pattern = re.compile(r"(def\\s+(\\w+)\\s*\\([^)]*\\)\\s*:.*?)(?=\\ndef\\s+transform|$)", re.DOTALL)',
    "            for m in pattern.finditer(code):",
    '                if m.group(2) != "transform":',
    "                    helpers.append(m.group(1))",
    "            return helpers",
    "        def extract_transform(code):",
    '            pattern = re.compile(r"(def\\s+transform\\s*\\([^)]*\\)\\s*:.*?$)", re.DOTALL)',
    "            m = pattern.search(code)",
    "            return m.group(1) if m else None",
    "        helpers1 = extract_helpers(code1)",
    "        helpers2 = extract_helpers(code2)",
    "        transform1 = extract_transform(code1)",
    "        transform2 = extract_transform(code2)",
    "        if transform1 and helpers2:",
    '            children.append("\\n".join(helpers2) + "\\n" + transform1)',
    "        if transform2 and helpers1:",
    '            children.append("\\n".join(helpers1) + "\\n" + transform2)',
    "        return children",
    "",
    "",
    "def evolutionary_synthesis(",
    "    initial_codes: List[Tuple[str, float, int]],",
    "    train_pairs: List[Dict],",
    "    population_size: int = EVOLUTIONARY_POPULATION,",
    "    generations: int = EVOLUTIONARY_GENERATIONS,",
    ") -> List[Tuple[str, float, int]]:",
    "    '''Evolve initial code candidates using mutation and crossover.'''",
    "    if not initial_codes:",
    "        return []",
    "    mutator = ProgramMutator()",
    "    population = {}",
    "    for code, score, passed in initial_codes:",
    '        h = hashlib.md5(code.encode()).hexdigest()[:12]',
    "        population[h] = (code, score, passed)",
    "    for gen in range(generations):",
    "        new_candidates = []",
    "        current_codes = [c for c, s, p in population.values()]",
    "        for code, score, passed in list(population.values()):",
    "            if score >= 1.0:",
    "                continue",
    "            for mutant in mutator.mutate_numeric(code)[:2]:",
    "                new_candidates.append(mutant)",
    "            for mutant in mutator.mutate_operations(code)[:2]:",
    "                new_candidates.append(mutant)",
    "            for mutant in mutator.mutate_color_value(code)[:1]:",
    "                new_candidates.append(mutant)",
    "            for mutant in mutator.mutate_indentation_logic(code)[:1]:",
    "                new_candidates.append(mutant)",
    "            for mutant in mutator.mutate_swap_lines(code)[:1]:",
    "                new_candidates.append(mutant)",
    "        top_codes = [c for c, s, p in sorted(population.values(), key=lambda x: -x[1])][:5]",
    "        for i in range(len(top_codes)):",
    "            for j in range(i+1, len(top_codes)):",
    "                children = mutator.crossover(top_codes[i], top_codes[j])",
    "                new_candidates.extend(children)",
    "        for candidate in new_candidates:",
    '            h = hashlib.md5(candidate.encode()).hexdigest()[:12]',
    "            if h in population:",
    "                continue",
    "            score, passed, total = verify_code_on_training(candidate, train_pairs)",
    "            if score > 0.0:",
    "                population[h] = (candidate, score, passed)",
    "        if len(population) > population_size:",
    "            sorted_items = sorted(population.items(), key=lambda x: -x[1][1])",
    "            population = dict(sorted_items[:population_size])",
    "        if any(s >= 1.0 for s, p in [(v[1], v[2]) for v in population.values()]):",
    "            break",
    "    results = sorted(population.values(), key=lambda x: (-x[1], -x[2]))",
    "    return results",
    "",
    "",
    'print("[EVOLUTION] Program synthesis engine ready (v3: swap-lines, pop=15, gens=4).")',
]
cells.append(code_cell(*llm_lines))

print(f"Generated {len(cells)} cells so far...")
with open("/tmp/v3_cells_part3.json", "w") as f:
    json.dump(cells, f)
print("Part 3 saved.")
